# Generated by pleme-linker resolve
# DO NOT EDIT - regenerate with: pleme-linker resolve --project .
#
# This file IS the lockfile. It contains:
# - All resolved packages with exact versions
# - Tarball URLs and integrity hashes (from npm registry)
# - Dependency relationships
#
# Nix uses fetchurl to download each package (cached in Attic),
# then pleme-linker build assembles node_modules.
{
  # Metadata
  generatedAt = "2025-11-26T04:55:26Z";
  resolverVersion = "0.3.0";
  packageCount = 261;

  # Root dependencies (direct deps from package.json)
  rootDependencies = [
    "@types/js-yaml@4.0.9"
    "@types/jsonwebtoken@9.0.10"
    "@types/node@20.19.25"
    "@types/ws@8.18.1"
    "js-yaml@4.1.1"
    "jsonwebtoken@9.0.2"
    "pino-pretty@10.3.1"
    "pino@8.21.0"
    "tsd@0.29.0"
    "typescript@5.9.3"
    "vitest@1.6.1"
    "ws@8.18.3"
    "zod@3.25.76"
  ];

  # All resolved packages
  packages = {
    "@babel/code-frame@7.27.1" = {
      pname = "@babel/code-frame";
      version = "7.27.1";
      url = "https://registry.npmjs.org/@babel/code-frame/-/code-frame-7.27.1.tgz";
      integrity = "sha512-cjQ7ZlQ0Mv3b47hABuTevyTuYN4i+loJKGeV9flcCgIK37cCXRh+L1bd3iBHlynerhQ7BhCkn2BPbQUL+rGqFg==";
      dependencies = [ "picocolors@1.1.1" "js-tokens@4.0.0" "@babel/helper-validator-identifier@7.28.5" ];
    };

    "@babel/helper-validator-identifier@7.28.5" = {
      pname = "@babel/helper-validator-identifier";
      version = "7.28.5";
      url = "https://registry.npmjs.org/@babel/helper-validator-identifier/-/helper-validator-identifier-7.28.5.tgz";
      integrity = "sha512-qSs4ifwzKJSV39ucNjsvc6WVHs6b7S03sOh2OcHF9UHfVPqWWALUsNUVzhSBiItjRZoLHx7nIarVjqKVusUZ1Q==";
    };

    "@esbuild/linux-arm64@0.21.5" = {
      pname = "@esbuild/linux-arm64";
      version = "0.21.5";
      url = "https://registry.npmjs.org/@esbuild/linux-arm64/-/linux-arm64-0.21.5.tgz";
      integrity = "sha512-ibKvmyYzKsBeX8d8I7MH/TMfWDXBF3db4qM6sy+7re0YXya+K1cem3on9XgdT2EQGMu4hQyZhan7TeQ8XkGp4Q==";
    };

    "@esbuild/linux-arm@0.21.5" = {
      pname = "@esbuild/linux-arm";
      version = "0.21.5";
      url = "https://registry.npmjs.org/@esbuild/linux-arm/-/linux-arm-0.21.5.tgz";
      integrity = "sha512-bPb5AHZtbeNGjCKVZ9UGqGwo8EUu4cLq68E95A53KlxAPRmUyYv2D6F0uUI65XisGOL1hBP5mTronbgo+0bFcA==";
    };

    "@esbuild/linux-ia32@0.21.5" = {
      pname = "@esbuild/linux-ia32";
      version = "0.21.5";
      url = "https://registry.npmjs.org/@esbuild/linux-ia32/-/linux-ia32-0.21.5.tgz";
      integrity = "sha512-YvjXDqLRqPDl2dvRODYmmhz4rPeVKYvppfGYKSNGdyZkA01046pLWyRKKI3ax8fbJoK5QbxblURkwK/MWY18Tg==";
    };

    "@esbuild/linux-loong64@0.21.5" = {
      pname = "@esbuild/linux-loong64";
      version = "0.21.5";
      url = "https://registry.npmjs.org/@esbuild/linux-loong64/-/linux-loong64-0.21.5.tgz";
      integrity = "sha512-uHf1BmMG8qEvzdrzAqg2SIG/02+4/DHB6a9Kbya0XDvwDEKCoC8ZRWI5JJvNdUjtciBGFQ5PuBlpEOXQj+JQSg==";
    };

    "@esbuild/linux-mips64el@0.21.5" = {
      pname = "@esbuild/linux-mips64el";
      version = "0.21.5";
      url = "https://registry.npmjs.org/@esbuild/linux-mips64el/-/linux-mips64el-0.21.5.tgz";
      integrity = "sha512-IajOmO+KJK23bj52dFSNCMsz1QP1DqM6cwLUv3W1QwyxkyIWecfafnI555fvSGqEKwjMXVLokcV5ygHW5b3Jbg==";
    };

    "@esbuild/linux-ppc64@0.21.5" = {
      pname = "@esbuild/linux-ppc64";
      version = "0.21.5";
      url = "https://registry.npmjs.org/@esbuild/linux-ppc64/-/linux-ppc64-0.21.5.tgz";
      integrity = "sha512-1hHV/Z4OEfMwpLO8rp7CvlhBDnjsC3CttJXIhBi+5Aj5r+MBvy4egg7wCbe//hSsT+RvDAG7s81tAvpL2XAE4w==";
    };

    "@esbuild/linux-riscv64@0.21.5" = {
      pname = "@esbuild/linux-riscv64";
      version = "0.21.5";
      url = "https://registry.npmjs.org/@esbuild/linux-riscv64/-/linux-riscv64-0.21.5.tgz";
      integrity = "sha512-2HdXDMd9GMgTGrPWnJzP2ALSokE/0O5HhTUvWIbD3YdjME8JwvSCnNGBnTThKGEB91OZhzrJ4qIIxk/SBmyDDA==";
    };

    "@esbuild/linux-s390x@0.21.5" = {
      pname = "@esbuild/linux-s390x";
      version = "0.21.5";
      url = "https://registry.npmjs.org/@esbuild/linux-s390x/-/linux-s390x-0.21.5.tgz";
      integrity = "sha512-zus5sxzqBJD3eXxwvjN1yQkRepANgxE9lgOW2qLnmr8ikMTphkjgXu1HR01K4FJg8h1kEEDAqDcZQtbrRnB41A==";
    };

    "@esbuild/linux-x64@0.21.5" = {
      pname = "@esbuild/linux-x64";
      version = "0.21.5";
      url = "https://registry.npmjs.org/@esbuild/linux-x64/-/linux-x64-0.21.5.tgz";
      integrity = "sha512-1rYdTpyv03iycF1+BhzrzQJCdOuAOtaqHTWJZCWvijKD2N5Xu0TtVC8/+1faWqcP9iBCWOmjmhoH94dH82BxPQ==";
    };

    "@jest/schemas@29.6.3" = {
      pname = "@jest/schemas";
      version = "29.6.3";
      url = "https://registry.npmjs.org/@jest/schemas/-/schemas-29.6.3.tgz";
      integrity = "sha512-mo5j5X+jIZmJQveBKeS/clAueipV7KgiX1vMgCxam1RNYiqE1w62n0/tJJnHtjW8ZHcQco5gY85jA3mi0L+nSA==";
      dependencies = [ "@sinclair/typebox@0.27.8" ];
    };

    "@jridgewell/sourcemap-codec@1.5.5" = {
      pname = "@jridgewell/sourcemap-codec";
      version = "1.5.5";
      url = "https://registry.npmjs.org/@jridgewell/sourcemap-codec/-/sourcemap-codec-1.5.5.tgz";
      integrity = "sha512-cYQ9310grqxueWbl+WuIUIaiUaDcj7WOq5fVhEljNVgRfOUhY9fy2zTvfoqWsnebh8Sl70VScFbICvJnLKB0Og==";
    };

    "@nodelib/fs.scandir@2.1.5" = {
      pname = "@nodelib/fs.scandir";
      version = "2.1.5";
      url = "https://registry.npmjs.org/@nodelib/fs.scandir/-/fs.scandir-2.1.5.tgz";
      integrity = "sha512-vq24Bq3ym5HEQm2NKCr3yXDwjc7vTsEThRDnkp2DK9p1uqLR+DHurm/NOTo0KG7HYHU7eppKZj3MyqYuMBf62g==";
      dependencies = [ "run-parallel@1.2.0" "@nodelib/fs.stat@2.0.5" ];
    };

    "@nodelib/fs.stat@2.0.5" = {
      pname = "@nodelib/fs.stat";
      version = "2.0.5";
      url = "https://registry.npmjs.org/@nodelib/fs.stat/-/fs.stat-2.0.5.tgz";
      integrity = "sha512-RkhPPp2zrqDAQA/2jNhnztcPAlv64XdhIp7a7454A5ovI7Bukxgt7MX7udwAu3zg1DcpPU0rz3VV1SeaqvY4+A==";
    };

    "@nodelib/fs.walk@1.2.8" = {
      pname = "@nodelib/fs.walk";
      version = "1.2.8";
      url = "https://registry.npmjs.org/@nodelib/fs.walk/-/fs.walk-1.2.8.tgz";
      integrity = "sha512-oGB+UxlgWcgQkgwo8GcEGwemoTFt3FIO9ababBmaGwXIoBKZ+GTy0pP185beGg7Llih/NSHSV2XAs1lnznocSg==";
      dependencies = [ "@nodelib/fs.scandir@2.1.5" "fastq@1.19.1" ];
    };

    "@rollup/rollup-linux-arm-gnueabihf@4.53.3" = {
      pname = "@rollup/rollup-linux-arm-gnueabihf";
      version = "4.53.3";
      url = "https://registry.npmjs.org/@rollup/rollup-linux-arm-gnueabihf/-/rollup-linux-arm-gnueabihf-4.53.3.tgz";
      integrity = "sha512-k9oD15soC/Ln6d2Wv/JOFPzZXIAIFLp6B+i14KhxAfnq76ajt0EhYc5YPeX6W1xJkAdItcVT+JhKl1QZh44/qw==";
    };

    "@rollup/rollup-linux-arm-musleabihf@4.53.3" = {
      pname = "@rollup/rollup-linux-arm-musleabihf";
      version = "4.53.3";
      url = "https://registry.npmjs.org/@rollup/rollup-linux-arm-musleabihf/-/rollup-linux-arm-musleabihf-4.53.3.tgz";
      integrity = "sha512-vTNlKq+N6CK/8UktsrFuc+/7NlEYVxgaEgRXVUVK258Z5ymho29skzW1sutgYjqNnquGwVUObAaxae8rZ6YMhg==";
    };

    "@rollup/rollup-linux-arm64-gnu@4.53.3" = {
      pname = "@rollup/rollup-linux-arm64-gnu";
      version = "4.53.3";
      url = "https://registry.npmjs.org/@rollup/rollup-linux-arm64-gnu/-/rollup-linux-arm64-gnu-4.53.3.tgz";
      integrity = "sha512-RGrFLWgMhSxRs/EWJMIFM1O5Mzuz3Xy3/mnxJp/5cVhZ2XoCAxJnmNsEyeMJtpK+wu0FJFWz+QF4mjCA7AUQ3w==";
    };

    "@rollup/rollup-linux-arm64-musl@4.53.3" = {
      pname = "@rollup/rollup-linux-arm64-musl";
      version = "4.53.3";
      url = "https://registry.npmjs.org/@rollup/rollup-linux-arm64-musl/-/rollup-linux-arm64-musl-4.53.3.tgz";
      integrity = "sha512-kASyvfBEWYPEwe0Qv4nfu6pNkITLTb32p4yTgzFCocHnJLAHs+9LjUu9ONIhvfT/5lv4YS5muBHyuV84epBo/A==";
    };

    "@rollup/rollup-linux-loong64-gnu@4.53.3" = {
      pname = "@rollup/rollup-linux-loong64-gnu";
      version = "4.53.3";
      url = "https://registry.npmjs.org/@rollup/rollup-linux-loong64-gnu/-/rollup-linux-loong64-gnu-4.53.3.tgz";
      integrity = "sha512-JiuKcp2teLJwQ7vkJ95EwESWkNRFJD7TQgYmCnrPtlu50b4XvT5MOmurWNrCj3IFdyjBQ5p9vnrX4JM6I8OE7g==";
    };

    "@rollup/rollup-linux-ppc64-gnu@4.53.3" = {
      pname = "@rollup/rollup-linux-ppc64-gnu";
      version = "4.53.3";
      url = "https://registry.npmjs.org/@rollup/rollup-linux-ppc64-gnu/-/rollup-linux-ppc64-gnu-4.53.3.tgz";
      integrity = "sha512-EoGSa8nd6d3T7zLuqdojxC20oBfNT8nexBbB/rkxgKj5T5vhpAQKKnD+h3UkoMuTyXkP5jTjK/ccNRmQrPNDuw==";
    };

    "@rollup/rollup-linux-riscv64-gnu@4.53.3" = {
      pname = "@rollup/rollup-linux-riscv64-gnu";
      version = "4.53.3";
      url = "https://registry.npmjs.org/@rollup/rollup-linux-riscv64-gnu/-/rollup-linux-riscv64-gnu-4.53.3.tgz";
      integrity = "sha512-4s+Wped2IHXHPnAEbIB0YWBv7SDohqxobiiPA1FIWZpX+w9o2i4LezzH/NkFUl8LRci/8udci6cLq+jJQlh+0g==";
    };

    "@rollup/rollup-linux-riscv64-musl@4.53.3" = {
      pname = "@rollup/rollup-linux-riscv64-musl";
      version = "4.53.3";
      url = "https://registry.npmjs.org/@rollup/rollup-linux-riscv64-musl/-/rollup-linux-riscv64-musl-4.53.3.tgz";
      integrity = "sha512-68k2g7+0vs2u9CxDt5ktXTngsxOQkSEV/xBbwlqYcUrAVh6P9EgMZvFsnHy4SEiUl46Xf0IObWVbMvPrr2gw8A==";
    };

    "@rollup/rollup-linux-s390x-gnu@4.53.3" = {
      pname = "@rollup/rollup-linux-s390x-gnu";
      version = "4.53.3";
      url = "https://registry.npmjs.org/@rollup/rollup-linux-s390x-gnu/-/rollup-linux-s390x-gnu-4.53.3.tgz";
      integrity = "sha512-VYsFMpULAz87ZW6BVYw3I6sWesGpsP9OPcyKe8ofdg9LHxSbRMd7zrVrr5xi/3kMZtpWL/wC+UIJWJYVX5uTKg==";
    };

    "@rollup/rollup-linux-x64-gnu@4.53.3" = {
      pname = "@rollup/rollup-linux-x64-gnu";
      version = "4.53.3";
      url = "https://registry.npmjs.org/@rollup/rollup-linux-x64-gnu/-/rollup-linux-x64-gnu-4.53.3.tgz";
      integrity = "sha512-3EhFi1FU6YL8HTUJZ51imGJWEX//ajQPfqWLI3BQq4TlvHy4X0MOr5q3D2Zof/ka0d5FNdPwZXm3Yyib/UEd+w==";
    };

    "@rollup/rollup-linux-x64-musl@4.53.3" = {
      pname = "@rollup/rollup-linux-x64-musl";
      version = "4.53.3";
      url = "https://registry.npmjs.org/@rollup/rollup-linux-x64-musl/-/rollup-linux-x64-musl-4.53.3.tgz";
      integrity = "sha512-eoROhjcc6HbZCJr+tvVT8X4fW3/5g/WkGvvmwz/88sDtSJzO7r/blvoBDgISDiCjDRZmHpwud7h+6Q9JxFwq1Q==";
    };

    "@sinclair/typebox@0.27.8" = {
      pname = "@sinclair/typebox";
      version = "0.27.8";
      url = "https://registry.npmjs.org/@sinclair/typebox/-/typebox-0.27.8.tgz";
      integrity = "sha512-+Fj43pSMwJs4KRrH/938Uf+uAELIgVBmQzg/q1YG10djyfA3TnrU8N8XzqCh/okZdszqBQTZf96idMfE5lnwTA==";
    };

    "@tsd/typescript@5.2.2" = {
      pname = "@tsd/typescript";
      version = "5.2.2";
      url = "https://registry.npmjs.org/@tsd/typescript/-/typescript-5.2.2.tgz";
      integrity = "sha512-VtjHPAKJqLJoHHKBDNofzvQB2+ZVxjXU/Gw6INAS9aINLQYVsxfzrQ2s84huCeYWZRTtrr7R0J7XgpZHjNwBCw==";
    };

    "@types/eslint@7.29.0" = {
      pname = "@types/eslint";
      version = "7.29.0";
      url = "https://registry.npmjs.org/@types/eslint/-/eslint-7.29.0.tgz";
      integrity = "sha512-VNcvioYDH8/FxaeTKkM4/TiTwt6pBV9E3OfGmvaw8tPl0rrHCJ4Ll15HRT+pMiFAf/MLQvAzC+6RzUMEL9Ceng==";
      dependencies = [ "@types/estree@1.0.8" "@types/json-schema@7.0.15" ];
    };

    "@types/estree@1.0.8" = {
      pname = "@types/estree";
      version = "1.0.8";
      url = "https://registry.npmjs.org/@types/estree/-/estree-1.0.8.tgz";
      integrity = "sha512-dWHzHa2WqEXI/O1E9OjrocMTKJl2mSrEolh1Iomrv6U+JuNwaHXsXx9bLu5gG7BUWFIN0skIQJQ/L1rIex4X6w==";
    };

    "@types/js-yaml@4.0.9" = {
      pname = "@types/js-yaml";
      version = "4.0.9";
      url = "https://registry.npmjs.org/@types/js-yaml/-/js-yaml-4.0.9.tgz";
      integrity = "sha512-k4MGaQl5TGo/iipqb2UDG2UwjXziSWkh0uysQelTlJpX1qGlpUZYm8PnO4DxG1qBomtJUdYJ6qR6xdIah10JLg==";
    };

    "@types/json-schema@7.0.15" = {
      pname = "@types/json-schema";
      version = "7.0.15";
      url = "https://registry.npmjs.org/@types/json-schema/-/json-schema-7.0.15.tgz";
      integrity = "sha512-5+fP8P8MFNC+AyZCDxrB2pkZFPGzqQWUzpSeuuVLvm8VMcorNYavBqoFcxK8bQz4Qsbn4oUEEem4wDLfcysGHA==";
    };

    "@types/jsonwebtoken@9.0.10" = {
      pname = "@types/jsonwebtoken";
      version = "9.0.10";
      url = "https://registry.npmjs.org/@types/jsonwebtoken/-/jsonwebtoken-9.0.10.tgz";
      integrity = "sha512-asx5hIG9Qmf/1oStypjanR7iKTv0gXQ1Ov/jfrX6kS/EO0OFni8orbmGCn0672NHR3kXHwpAwR+B368ZGN/2rA==";
      dependencies = [ "@types/ms@2.1.0" "@types/node@20.19.25" ];
    };

    "@types/minimist@1.2.5" = {
      pname = "@types/minimist";
      version = "1.2.5";
      url = "https://registry.npmjs.org/@types/minimist/-/minimist-1.2.5.tgz";
      integrity = "sha512-hov8bUuiLiyFPGyFPE1lwWhmzYbirOXQNNo40+y3zow8aFVTeyn3VWL0VFFfdNddA8S4Vf0Tc062rzyNr7Paag==";
    };

    "@types/ms@2.1.0" = {
      pname = "@types/ms";
      version = "2.1.0";
      url = "https://registry.npmjs.org/@types/ms/-/ms-2.1.0.tgz";
      integrity = "sha512-GsCCIZDE/p3i96vtEqx+7dBUGXrc7zeSK3wwPHIaRThS+9OhWIXRqzs4d6k1SVU8g91DrNRWxWUGhp5KXQb2VA==";
    };

    "@types/node@20.19.25" = {
      pname = "@types/node";
      version = "20.19.25";
      url = "https://registry.npmjs.org/@types/node/-/node-20.19.25.tgz";
      integrity = "sha512-ZsJzA5thDQMSQO788d7IocwwQbI8B5OPzmqNvpf3NY/+MHDAS759Wo0gd2WQeXYt5AAAQjzcrTVC6SKCuYgoCQ==";
      dependencies = [ "undici-types@6.21.0" ];
    };

    "@types/normalize-package-data@2.4.4" = {
      pname = "@types/normalize-package-data";
      version = "2.4.4";
      url = "https://registry.npmjs.org/@types/normalize-package-data/-/normalize-package-data-2.4.4.tgz";
      integrity = "sha512-37i+OaWTh9qeK4LSHPsyRC7NahnGotNuZvjLSgcPzblpHB3rrCJxAOgI5gCdKm7coonsaX1Of0ILiTcnZjbfxA==";
    };

    "@types/ws@8.18.1" = {
      pname = "@types/ws";
      version = "8.18.1";
      url = "https://registry.npmjs.org/@types/ws/-/ws-8.18.1.tgz";
      integrity = "sha512-ThVF6DCVhA8kUGy+aazFQ4kXQ7E1Ty7A3ypFOe0IcJV8O/M511G99AW24irKrW56Wt44yG9+ij8FaqoBGkuBXg==";
      dependencies = [ "@types/node@20.19.25" ];
    };

    "@vitest/expect@1.6.1" = {
      pname = "@vitest/expect";
      version = "1.6.1";
      url = "https://registry.npmjs.org/@vitest/expect/-/expect-1.6.1.tgz";
      integrity = "sha512-jXL+9+ZNIJKruofqXuuTClf44eSpcHlgj3CiuNihUF3Ioujtmc0zIa3UJOW5RjDK1YLBJZnWBlPuqhYycLioog==";
      dependencies = [ "chai@4.5.0" "@vitest/utils@1.6.1" "@vitest/spy@1.6.1" ];
    };

    "@vitest/runner@1.6.1" = {
      pname = "@vitest/runner";
      version = "1.6.1";
      url = "https://registry.npmjs.org/@vitest/runner/-/runner-1.6.1.tgz";
      integrity = "sha512-3nSnYXkVkf3mXFfE7vVyPmi3Sazhb/2cfZGGs0JRzFsPFvAMBEcrweV1V1GsrstdXeKCTXlJbvnQwGWgEIHmOA==";
      dependencies = [ "p-limit@5.0.0" "pathe@1.1.2" "@vitest/utils@1.6.1" ];
    };

    "@vitest/snapshot@1.6.1" = {
      pname = "@vitest/snapshot";
      version = "1.6.1";
      url = "https://registry.npmjs.org/@vitest/snapshot/-/snapshot-1.6.1.tgz";
      integrity = "sha512-WvidQuWAzU2p95u8GAKlRMqMyN1yOJkGHnx3M1PL9Raf7AQ1kwLKg04ADlCa3+OXUZE7BceOhVZiuWAbzCKcUQ==";
      dependencies = [ "magic-string@0.30.21" "pretty-format@29.7.0" "pathe@1.1.2" ];
    };

    "@vitest/spy@1.6.1" = {
      pname = "@vitest/spy";
      version = "1.6.1";
      url = "https://registry.npmjs.org/@vitest/spy/-/spy-1.6.1.tgz";
      integrity = "sha512-MGcMmpGkZebsMZhbQKkAf9CX5zGvjkBTqf8Zx3ApYWXr3wG+QvEu2eXWfnIIWYSJExIp4V9FCKDEeygzkYrXMw==";
      dependencies = [ "tinyspy@2.2.1" ];
    };

    "@vitest/utils@1.6.1" = {
      pname = "@vitest/utils";
      version = "1.6.1";
      url = "https://registry.npmjs.org/@vitest/utils/-/utils-1.6.1.tgz";
      integrity = "sha512-jOrrUvXM4Av9ZWiG1EajNto0u96kWAhJ1LmPmJhXXQx/32MecEKd10pOLYgS2BQx1TgkGhloPU1ArDW2vvaY6g==";
      dependencies = [ "loupe@2.3.7" "diff-sequences@29.6.3" "estree-walker@3.0.3" "pretty-format@29.7.0" ];
    };

    "abort-controller@3.0.0" = {
      pname = "abort-controller";
      version = "3.0.0";
      url = "https://registry.npmjs.org/abort-controller/-/abort-controller-3.0.0.tgz";
      integrity = "sha512-h8lQ8tacZYnR3vNQTgibj+tODHI5/+l06Au2Pcriv/Gmet0eaj4TwWH41sO9wnHDiQsEj19q0drzdWdeAHtweg==";
      dependencies = [ "event-target-shim@5.0.1" ];
    };

    "acorn-walk@8.3.4" = {
      pname = "acorn-walk";
      version = "8.3.4";
      url = "https://registry.npmjs.org/acorn-walk/-/acorn-walk-8.3.4.tgz";
      integrity = "sha512-ueEepnujpqee2o5aIYnvHU6C0A42MNdsIDeqy5BydrkuC5R1ZuUFnm27EeFJGoEHJQgn3uleRvmTXaJgfXbt4g==";
      dependencies = [ "acorn@8.15.0" ];
    };

    "acorn@8.15.0" = {
      pname = "acorn";
      version = "8.15.0";
      url = "https://registry.npmjs.org/acorn/-/acorn-8.15.0.tgz";
      integrity = "sha512-NZyJarBfL7nWwIq+FDL6Zp/yHEhePMNnnJ0y3qfieCrmNvYct8uvtiV41UvlSe6apAfk0fY1FbWx+NwfmpvtTg==";
      hasBin = true;
    };

    "ansi-escapes@4.3.2" = {
      pname = "ansi-escapes";
      version = "4.3.2";
      url = "https://registry.npmjs.org/ansi-escapes/-/ansi-escapes-4.3.2.tgz";
      integrity = "sha512-gKXj5ALrKWQLsYG9jlTRmR/xKluxHV+Z9QEwNIgCfM1/uwPMCuzVVnh5mwTd+OuBZcwSIMbqssNWRm1lE51QaQ==";
      dependencies = [ "type-fest@0.21.3" ];
    };

    "ansi-regex@5.0.1" = {
      pname = "ansi-regex";
      version = "5.0.1";
      url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-5.0.1.tgz";
      integrity = "sha512-quJQXlTSUGL2LH9SUXo8VwsY4soanhgo6LNSm84E1LBcE8s3O0wpdiRzyR9z/ZZJMlMWv37qOOb9pdJlMUEKFQ==";
    };

    "ansi-styles@4.3.0" = {
      pname = "ansi-styles";
      version = "4.3.0";
      url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz";
      integrity = "sha512-zbB9rCJAT1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg==";
      dependencies = [ "color-convert@2.0.1" ];
    };

    "ansi-styles@5.2.0" = {
      pname = "ansi-styles";
      version = "5.2.0";
      url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-5.2.0.tgz";
      integrity = "sha512-Cxwpt2SfTzTtXcfOlzGEee8O+c+MmUgGrNiBcXnuWxuFJHe6a5Hz7qwhwe5OgaSYI0IJvkLqWX1ASG+cJOkEiA==";
    };

    "argparse@2.0.1" = {
      pname = "argparse";
      version = "2.0.1";
      url = "https://registry.npmjs.org/argparse/-/argparse-2.0.1.tgz";
      integrity = "sha512-8+9WqebbFzpX9OR+Wa6O29asIogeRMzcGtAINdpMHHyAg10f05aSFVBbcEqGf/PXw1EjAZ+q2/bEBg3DvurK3Q==";
    };

    "array-union@2.1.0" = {
      pname = "array-union";
      version = "2.1.0";
      url = "https://registry.npmjs.org/array-union/-/array-union-2.1.0.tgz";
      integrity = "sha512-HGyxoOTYUyCM6stUe6EJgnd4EoewAI7zMdfqO+kGjnlZmBDz/cR5pf8r/cR4Wq60sL/p0IkcjUEEPwS3GFrIyw==";
    };

    "arrify@1.0.1" = {
      pname = "arrify";
      version = "1.0.1";
      url = "https://registry.npmjs.org/arrify/-/arrify-1.0.1.tgz";
      integrity = "sha512-3CYzex9M9FGQjCGMGyi6/31c8GJbgb0qGyrx5HWxPd0aCwh4cB2YjMb2Xf9UuoogrMrlO9cTqnB5rI5GHZTcUA==";
    };

    "assertion-error@1.1.0" = {
      pname = "assertion-error";
      version = "1.1.0";
      url = "https://registry.npmjs.org/assertion-error/-/assertion-error-1.1.0.tgz";
      integrity = "sha512-jgsaNduz+ndvGyFt3uSuWqvy4lCnIJiovtouQN5JZHOKCS2QuhEdbcQHFhVksz2N2U9hXJo8odG7ETyWlEeuDw==";
    };

    "atomic-sleep@1.0.0" = {
      pname = "atomic-sleep";
      version = "1.0.0";
      url = "https://registry.npmjs.org/atomic-sleep/-/atomic-sleep-1.0.0.tgz";
      integrity = "sha512-kNOjDqAh7px0XWNI+4QbzoiR/nTkHAWNud2uvnJquD1/x5a7EQZMJT0AczqK0Qn67oY/TTQ1LbUKajZpp3I9tQ==";
    };

    "base64-js@1.5.1" = {
      pname = "base64-js";
      version = "1.5.1";
      url = "https://registry.npmjs.org/base64-js/-/base64-js-1.5.1.tgz";
      integrity = "sha512-AKpaYlHn8t4SVbOHCy+b5+KKgvR4vrsD8vbvrbiQJps7fKDTkjkDry6ji0rUJjC0kzbNePLwzxq8iypo41qeWA==";
    };

    "braces@3.0.3" = {
      pname = "braces";
      version = "3.0.3";
      url = "https://registry.npmjs.org/braces/-/braces-3.0.3.tgz";
      integrity = "sha512-yQbXgO/OSZVD2IsiLlro+7Hf6Q18EJrKSEsdoMzKePKXct3gvD8oLcOQdIzGupr5Fj+EDe8gO/lxc1BzfMpxvA==";
      dependencies = [ "fill-range@7.1.1" ];
    };

    "buffer-equal-constant-time@1.0.1" = {
      pname = "buffer-equal-constant-time";
      version = "1.0.1";
      url = "https://registry.npmjs.org/buffer-equal-constant-time/-/buffer-equal-constant-time-1.0.1.tgz";
      integrity = "sha512-zRpUiDwd/xk6ADqPMATG8vc9VPrkck7T07OIx0gnjmJAnHnTVXNQG3vfvWNuiZIkwu9KrKdA1iJKfsfTVxE6NA==";
    };

    "buffer@6.0.3" = {
      pname = "buffer";
      version = "6.0.3";
      url = "https://registry.npmjs.org/buffer/-/buffer-6.0.3.tgz";
      integrity = "sha512-FTiCpNxtwiZZHEZbcbTIcZjERVICn9yq/pDFkTl95/AxzD1naBctN7YO68riM/gLSDY7sdrMby8hofADYuuqOA==";
      dependencies = [ "base64-js@1.5.1" "ieee754@1.2.1" ];
    };

    "cac@6.7.14" = {
      pname = "cac";
      version = "6.7.14";
      url = "https://registry.npmjs.org/cac/-/cac-6.7.14.tgz";
      integrity = "sha512-b6Ilus+c3RrdDk+JhLKUAQfzzgLEPy6wcXqS7f/xe1EETvsDP6GORG7SFuOs6cID5YkqchW/LXZbX5bc8j7ZcQ==";
    };

    "camelcase-keys@6.2.2" = {
      pname = "camelcase-keys";
      version = "6.2.2";
      url = "https://registry.npmjs.org/camelcase-keys/-/camelcase-keys-6.2.2.tgz";
      integrity = "sha512-YrwaA0vEKazPBkn0ipTiMpSajYDSe+KjQfrjhcBMxJt/znbvlHd8Pw/Vamaz5EB4Wfhs3SUR3Z9mwRu/P3s3Yg==";
      dependencies = [ "camelcase@5.3.1" "map-obj@4.3.0" "quick-lru@4.0.1" ];
    };

    "camelcase@5.3.1" = {
      pname = "camelcase";
      version = "5.3.1";
      url = "https://registry.npmjs.org/camelcase/-/camelcase-5.3.1.tgz";
      integrity = "sha512-L28STB170nwWS63UjtlEOE3dldQApaJXZkOI1uMFfzf3rRuPegHaHesyee+YxQ+W6SvRDQV6UrdOdRiR153wJg==";
    };

    "chai@4.5.0" = {
      pname = "chai";
      version = "4.5.0";
      url = "https://registry.npmjs.org/chai/-/chai-4.5.0.tgz";
      integrity = "sha512-RITGBfijLkBddZvnn8jdqoTypxvqbOLYQkGGxXzeFjVHvudaPw0HNFD9x928/eUwYWd2dPCugVqspGALTZZQKw==";
      dependencies = [ "deep-eql@4.1.4" "get-func-name@2.0.2" "assertion-error@1.1.0" "type-detect@4.1.0" "check-error@1.0.3" "loupe@2.3.7" "pathval@1.1.1" ];
    };

    "chalk@4.1.2" = {
      pname = "chalk";
      version = "4.1.2";
      url = "https://registry.npmjs.org/chalk/-/chalk-4.1.2.tgz";
      integrity = "sha512-oKnbhFyRIXpUuez8iBMmyEa4nbj4IOQyuhc/wy9kY7/WVPcwIO9VA668Pu8RkO7+0G76SLROeyw9CpQ061i4mA==";
      dependencies = [ "supports-color@7.2.0" "ansi-styles@4.3.0" ];
    };

    "check-error@1.0.3" = {
      pname = "check-error";
      version = "1.0.3";
      url = "https://registry.npmjs.org/check-error/-/check-error-1.0.3.tgz";
      integrity = "sha512-iKEoDYaRmd1mxM90a2OEfWhjsjPpYPuQ+lMYsoxB126+t8fw7ySEO48nmDg5COTjxDI65/Y2OWpeEHk3ZOe8zg==";
      dependencies = [ "get-func-name@2.0.2" ];
    };

    "color-convert@2.0.1" = {
      pname = "color-convert";
      version = "2.0.1";
      url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
      integrity = "sha512-RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
      dependencies = [ "color-name@1.1.4" ];
    };

    "color-name@1.1.4" = {
      pname = "color-name";
      version = "1.1.4";
      url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
      integrity = "sha512-dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
    };

    "colorette@2.0.20" = {
      pname = "colorette";
      version = "2.0.20";
      url = "https://registry.npmjs.org/colorette/-/colorette-2.0.20.tgz";
      integrity = "sha512-IfEDxwoWIjkeXL1eXcDiow4UbKjhLdq6/EuSVR9GMN7KVH3r9gQ83e73hsz1Nd1T3ijd5xv1wcWRYO+D6kCI2w==";
    };

    "confbox@0.1.8" = {
      pname = "confbox";
      version = "0.1.8";
      url = "https://registry.npmjs.org/confbox/-/confbox-0.1.8.tgz";
      integrity = "sha512-RMtmw0iFkeR4YV+fUOSucriAQNb9g8zFR52MWCtl+cCZOFRNL6zeB395vPzFhEjjn4fMxXudmELnl/KF/WrK6w==";
    };

    "cross-spawn@7.0.6" = {
      pname = "cross-spawn";
      version = "7.0.6";
      url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-7.0.6.tgz";
      integrity = "sha512-uV2QOWP2nWzsy2aMp8aRibhi9dlzF5Hgh5SHaB9OiTGEyDTiJJyx0uy51QXdyWbtAHNua4XJzUKca3OzKUd3vA==";
      dependencies = [ "shebang-command@2.0.0" "which@2.0.2" "path-key@3.1.1" ];
    };

    "dateformat@4.6.3" = {
      pname = "dateformat";
      version = "4.6.3";
      url = "https://registry.npmjs.org/dateformat/-/dateformat-4.6.3.tgz";
      integrity = "sha512-2P0p0pFGzHS5EMnhdxQi7aJN+iMheud0UhG4dlE1DLAlvL8JHjJJTX/CSm4JXwV0Ka5nGk3zC5mcb5bUQUxxMA==";
    };

    "debug@4.4.3" = {
      pname = "debug";
      version = "4.4.3";
      url = "https://registry.npmjs.org/debug/-/debug-4.4.3.tgz";
      integrity = "sha512-RGwwWnwQvkVfavKVt22FGLw+xYSdzARwm0ru6DhTVA3umU5hZc28V3kO4stgYryrTlLpuvgI9GiijltAjNbcqA==";
      dependencies = [ "ms@2.1.3" ];
    };

    "decamelize-keys@1.1.1" = {
      pname = "decamelize-keys";
      version = "1.1.1";
      url = "https://registry.npmjs.org/decamelize-keys/-/decamelize-keys-1.1.1.tgz";
      integrity = "sha512-WiPxgEirIV0/eIOMcnFBA3/IJZAZqKnwAwWyvvdi4lsr1WCN22nhdf/3db3DoZcUjTV2SqfzIwNyp6y2xs3nmg==";
      dependencies = [ "map-obj@1.0.1" "decamelize@1.2.0" ];
    };

    "decamelize@1.2.0" = {
      pname = "decamelize";
      version = "1.2.0";
      url = "https://registry.npmjs.org/decamelize/-/decamelize-1.2.0.tgz";
      integrity = "sha512-z2S+W9X73hAUUki+N+9Za2lBlun89zigOyGrsax+KUQ6wKW4ZoWpEYBkGhQjwAjjDCkWxhY0VKEhk8wzY7F5cA==";
    };

    "deep-eql@4.1.4" = {
      pname = "deep-eql";
      version = "4.1.4";
      url = "https://registry.npmjs.org/deep-eql/-/deep-eql-4.1.4.tgz";
      integrity = "sha512-SUwdGfqdKOwxCPeVYjwSyRpJ7Z+fhpwIAtmCUdZIWZ/YP5R9WAsyuSgpLVDi9bjWoN2LXHNss/dk3urXtdQxGg==";
      dependencies = [ "type-detect@4.1.0" ];
    };

    "diff-sequences@29.6.3" = {
      pname = "diff-sequences";
      version = "29.6.3";
      url = "https://registry.npmjs.org/diff-sequences/-/diff-sequences-29.6.3.tgz";
      integrity = "sha512-EjePK1srD3P08o2j4f0ExnylqRs5B9tJjcp9t1krH2qRi8CCdsYfwe9JgSLurFBWwq4uOlipzfk5fHNvwFKr8Q==";
    };

    "dir-glob@3.0.1" = {
      pname = "dir-glob";
      version = "3.0.1";
      url = "https://registry.npmjs.org/dir-glob/-/dir-glob-3.0.1.tgz";
      integrity = "sha512-WkrWp9GR4KXfKGYzOLmTuGVi1UWFfws377n9cc55/tb6DuqyF6pcQ5AbiHEshaDpY9v6oaSr2XCDidGmMwdzIA==";
      dependencies = [ "path-type@4.0.0" ];
    };

    "ecdsa-sig-formatter@1.0.11" = {
      pname = "ecdsa-sig-formatter";
      version = "1.0.11";
      url = "https://registry.npmjs.org/ecdsa-sig-formatter/-/ecdsa-sig-formatter-1.0.11.tgz";
      integrity = "sha512-nagl3RYrbNv6kQkeJIpt6NJZy8twLB/2vtz6yN9Z4vRKHN4/QZJIEbqohALSgwKdnksuY3k5Addp5lg8sVoVcQ==";
      dependencies = [ "safe-buffer@5.2.1" ];
    };

    "emoji-regex@8.0.0" = {
      pname = "emoji-regex";
      version = "8.0.0";
      url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-8.0.0.tgz";
      integrity = "sha512-MSjYzcWNOA0ewAHpz0MxpYFvwg6yjy1NG3xteoqz644VCo/RPgnr1/GGt+ic3iJTzQ8Eu3TdM14SawnVUmGE6A==";
    };

    "end-of-stream@1.4.5" = {
      pname = "end-of-stream";
      version = "1.4.5";
      url = "https://registry.npmjs.org/end-of-stream/-/end-of-stream-1.4.5.tgz";
      integrity = "sha512-ooEGc6HP26xXq/N+GCGOT0JKCLDGrq2bQUZrQ7gyrJiZANJ/8YDTxTpQBXGMn+WbIQXNVpyWymm7KYVICQnyOg==";
      dependencies = [ "once@1.4.0" ];
    };

    "error-ex@1.3.4" = {
      pname = "error-ex";
      version = "1.3.4";
      url = "https://registry.npmjs.org/error-ex/-/error-ex-1.3.4.tgz";
      integrity = "sha512-sqQamAnR14VgCr1A618A3sGrygcpK+HEbenA/HiEAkkUwcZIIB/tgWqHFxWgOyDh4nB4JCRimh79dR5Ywc9MDQ==";
      dependencies = [ "is-arrayish@0.2.1" ];
    };

    "esbuild@0.21.5" = {
      pname = "esbuild";
      version = "0.21.5";
      url = "https://registry.npmjs.org/esbuild/-/esbuild-0.21.5.tgz";
      integrity = "sha512-mg3OPMV4hXywwpoDxu3Qda5xCKQi+vCTZq8S9J/EpkhB2HzKXq4SNFZE3+NK93JYxc8VMSep+lOUSC/RVKaBqw==";
      dependencies = [ "@esbuild/linux-s390x@0.21.5" "@esbuild/linux-loong64@0.21.5" "@esbuild/linux-mips64el@0.21.5" "@esbuild/linux-arm64@0.21.5" "@esbuild/linux-ppc64@0.21.5" "@esbuild/linux-ia32@0.21.5" "@esbuild/linux-riscv64@0.21.5" "@esbuild/linux-arm@0.21.5" "@esbuild/linux-x64@0.21.5" ];
      hasBin = true;
    };

    "eslint-formatter-pretty@4.1.0" = {
      pname = "eslint-formatter-pretty";
      version = "4.1.0";
      url = "https://registry.npmjs.org/eslint-formatter-pretty/-/eslint-formatter-pretty-4.1.0.tgz";
      integrity = "sha512-IsUTtGxF1hrH6lMWiSl1WbGaiP01eT6kzywdY1U+zLc0MP+nwEnUiS9UI8IaOTUhTeQJLlCEWIbXINBH4YJbBQ==";
      dependencies = [ "log-symbols@4.1.0" "string-width@4.2.3" "eslint-rule-docs@1.1.235" "supports-hyperlinks@2.3.0" "plur@4.0.0" "chalk@4.1.2" "@types/eslint@7.29.0" "ansi-escapes@4.3.2" ];
    };

    "eslint-rule-docs@1.1.235" = {
      pname = "eslint-rule-docs";
      version = "1.1.235";
      url = "https://registry.npmjs.org/eslint-rule-docs/-/eslint-rule-docs-1.1.235.tgz";
      integrity = "sha512-+TQ+x4JdTnDoFEXXb3fDvfGOwnyNV7duH8fXWTPD1ieaBmB8omj7Gw/pMBBu4uI2uJCCU8APDaQJzWuXnTsH4A==";
    };

    "estree-walker@3.0.3" = {
      pname = "estree-walker";
      version = "3.0.3";
      url = "https://registry.npmjs.org/estree-walker/-/estree-walker-3.0.3.tgz";
      integrity = "sha512-7RUKfXgSMMkzt6ZuXmqapOurLGPPfgj6l9uRZ7lRGolvk0y2yocc35LdcxKC5PQZdn2DMqioAQ2NoWcrTKmm6g==";
      dependencies = [ "@types/estree@1.0.8" ];
    };

    "event-target-shim@5.0.1" = {
      pname = "event-target-shim";
      version = "5.0.1";
      url = "https://registry.npmjs.org/event-target-shim/-/event-target-shim-5.0.1.tgz";
      integrity = "sha512-i/2XbnSz/uxRCU6+NdVJgKWDTM427+MqYbkQzD321DuCQJUqOuJKIA0IM2+W2xtYHdKOmZ4dR6fExsd4SXL+WQ==";
    };

    "events@3.3.0" = {
      pname = "events";
      version = "3.3.0";
      url = "https://registry.npmjs.org/events/-/events-3.3.0.tgz";
      integrity = "sha512-mQw+2fkQbALzQ7V0MY0IqdnXNOeTtP4r0lN9z7AAawCXgqea7bDii20AYrIBrFd/Hx0M2Ocz6S111CaFkUcb0Q==";
    };

    "execa@8.0.1" = {
      pname = "execa";
      version = "8.0.1";
      url = "https://registry.npmjs.org/execa/-/execa-8.0.1.tgz";
      integrity = "sha512-VyhnebXciFV2DESc+p6B+y0LjSm0krU4OgJN44qFAhBY0TJ+1V61tYD2+wHusZ6F9n5K+vl8k0sTy7PEfV4qpg==";
      dependencies = [ "merge-stream@2.0.0" "human-signals@5.0.0" "cross-spawn@7.0.6" "strip-final-newline@3.0.0" "is-stream@3.0.0" "onetime@6.0.0" "get-stream@8.0.1" "signal-exit@4.1.0" "npm-run-path@5.3.0" ];
    };

    "fast-copy@3.0.2" = {
      pname = "fast-copy";
      version = "3.0.2";
      url = "https://registry.npmjs.org/fast-copy/-/fast-copy-3.0.2.tgz";
      integrity = "sha512-dl0O9Vhju8IrcLndv2eU4ldt1ftXMqqfgN4H1cpmGV7P6jeB9FwpN9a2c8DPGE1Ys88rNUJVYDHq73CGAGOPfQ==";
    };

    "fast-glob@3.3.3" = {
      pname = "fast-glob";
      version = "3.3.3";
      url = "https://registry.npmjs.org/fast-glob/-/fast-glob-3.3.3.tgz";
      integrity = "sha512-7MptL8U0cqcFdzIzwOTHoilX9x5BrNqye7Z/LuC7kCMRio1EMSyqRK3BEAUD7sXRq4iT4AzTVuZdhgQ2TCvYLg==";
      dependencies = [ "merge2@1.4.1" "micromatch@4.0.8" "@nodelib/fs.stat@2.0.5" "@nodelib/fs.walk@1.2.8" "glob-parent@5.1.2" ];
    };

    "fast-redact@3.5.0" = {
      pname = "fast-redact";
      version = "3.5.0";
      url = "https://registry.npmjs.org/fast-redact/-/fast-redact-3.5.0.tgz";
      integrity = "sha512-dwsoQlS7h9hMeYUq1W++23NDcBLV4KqONnITDV9DjfS3q1SgDGVrBdvvTLUotWtPSD7asWDV9/CmsZPy8Hf70A==";
    };

    "fast-safe-stringify@2.1.1" = {
      pname = "fast-safe-stringify";
      version = "2.1.1";
      url = "https://registry.npmjs.org/fast-safe-stringify/-/fast-safe-stringify-2.1.1.tgz";
      integrity = "sha512-W+KJc2dmILlPplD/H4K9l9LcAHAfPtP6BY84uVLXQ6Evcz9Lcg33Y2z1IVblT6xdY54PXYVHEv+0Wpq8Io6zkA==";
    };

    "fastq@1.19.1" = {
      pname = "fastq";
      version = "1.19.1";
      url = "https://registry.npmjs.org/fastq/-/fastq-1.19.1.tgz";
      integrity = "sha512-GwLTyxkCXjXbxqIhTsMI2Nui8huMPtnxg7krajPJAjnEG/iiOS7i+zCtWGZR9G0NBKbXKh6X9m9UIsYX/N6vvQ==";
      dependencies = [ "reusify@1.1.0" ];
    };

    "fill-range@7.1.1" = {
      pname = "fill-range";
      version = "7.1.1";
      url = "https://registry.npmjs.org/fill-range/-/fill-range-7.1.1.tgz";
      integrity = "sha512-YsGpe3WHLK8ZYi4tWDg2Jy3ebRz2rXowDxnld4bkQB00cc/1Zw9AWnC0i9ztDJitivtQvaI9KaLyKrc+hBW0yg==";
      dependencies = [ "to-regex-range@5.0.1" ];
    };

    "find-up@4.1.0" = {
      pname = "find-up";
      version = "4.1.0";
      url = "https://registry.npmjs.org/find-up/-/find-up-4.1.0.tgz";
      integrity = "sha512-PpOwAdQ/YlXQ2vj8a3h8IipDuYRi3wceVQQGYWxNINccq40Anw7BlsEXCMbt1Zt+OLA6Fq9suIpIWD0OsnISlw==";
      dependencies = [ "locate-path@5.0.0" "path-exists@4.0.0" ];
    };

    "function-bind@1.1.2" = {
      pname = "function-bind";
      version = "1.1.2";
      url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.2.tgz";
      integrity = "sha512-7XHNxH7qX9xG5mIwxkhumTox/MIRNcOgDrxWsMt2pAr23WHp6MrRlN7FBSFpCpr+oVO0F744iUgR82nJMfG2SA==";
    };

    "get-func-name@2.0.2" = {
      pname = "get-func-name";
      version = "2.0.2";
      url = "https://registry.npmjs.org/get-func-name/-/get-func-name-2.0.2.tgz";
      integrity = "sha512-8vXOvuE167CtIc3OyItco7N/dpRtBbYOsPsXCz7X/PMnlGjYjSGuZJgM1Y7mmew7BKf9BqvLX2tnOVy1BBUsxQ==";
    };

    "get-stream@8.0.1" = {
      pname = "get-stream";
      version = "8.0.1";
      url = "https://registry.npmjs.org/get-stream/-/get-stream-8.0.1.tgz";
      integrity = "sha512-VaUJspBffn/LMCJVoMvSAdmscJyS1auj5Zulnn5UoYcY531UWmdwhRWkcGKnGU93m5HSXP9LP2usOryrBtQowA==";
    };

    "glob-parent@5.1.2" = {
      pname = "glob-parent";
      version = "5.1.2";
      url = "https://registry.npmjs.org/glob-parent/-/glob-parent-5.1.2.tgz";
      integrity = "sha512-AOIgSQCepiJYwP3ARnGx+5VnTu2HBYdzbGP45eLw1vr3zB3vZLeyed1sC9hnbcOc9/SrMyM5RPQrkGz4aS9Zow==";
      dependencies = [ "is-glob@4.0.3" ];
    };

    "globby@11.1.0" = {
      pname = "globby";
      version = "11.1.0";
      url = "https://registry.npmjs.org/globby/-/globby-11.1.0.tgz";
      integrity = "sha512-jhIXaOzy1sb8IyocaruWSn1TjmnBVs8Ayhcy83rmxNJ8q2uWKCAj3CnJY+KpGSXCueAPc0i05kVvVKtP1t9S3g==";
      dependencies = [ "slash@3.0.0" "ignore@5.3.2" "merge2@1.4.1" "fast-glob@3.3.3" "dir-glob@3.0.1" "array-union@2.1.0" ];
    };

    "hard-rejection@2.1.0" = {
      pname = "hard-rejection";
      version = "2.1.0";
      url = "https://registry.npmjs.org/hard-rejection/-/hard-rejection-2.1.0.tgz";
      integrity = "sha512-VIZB+ibDhx7ObhAe7OVtoEbuP4h/MuOTHJ+J8h/eBXotJYl0fBgR72xDFCKgIh22OJZIOVNxBMWuhAr10r8HdA==";
    };

    "has-flag@4.0.0" = {
      pname = "has-flag";
      version = "4.0.0";
      url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
      integrity = "sha512-EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
    };

    "hasown@2.0.2" = {
      pname = "hasown";
      version = "2.0.2";
      url = "https://registry.npmjs.org/hasown/-/hasown-2.0.2.tgz";
      integrity = "sha512-0hJU9SCPvmMzIBdZFqNPXWa6dqh7WdH0cII9y+CyS8rG3nL48Bclra9HmKhVVUHyPWNH5Y7xDwAB7bfgSjkUMQ==";
      dependencies = [ "function-bind@1.1.2" ];
    };

    "help-me@5.0.0" = {
      pname = "help-me";
      version = "5.0.0";
      url = "https://registry.npmjs.org/help-me/-/help-me-5.0.0.tgz";
      integrity = "sha512-7xgomUX6ADmcYzFik0HzAxh/73YlKR9bmFzf51CZwR+b6YtzU2m0u49hQCqV6SvlqIqsaxovfwdvbnsw3b/zpg==";
    };

    "hosted-git-info@2.8.9" = {
      pname = "hosted-git-info";
      version = "2.8.9";
      url = "https://registry.npmjs.org/hosted-git-info/-/hosted-git-info-2.8.9.tgz";
      integrity = "sha512-mxIDAb9Lsm6DoOJ7xH+5+X4y1LU/4Hi50L9C5sIswK3JzULS4bwk1FvjdBgvYR4bzT4tuUQiC15FE2f5HbLvYw==";
    };

    "hosted-git-info@4.1.0" = {
      pname = "hosted-git-info";
      version = "4.1.0";
      url = "https://registry.npmjs.org/hosted-git-info/-/hosted-git-info-4.1.0.tgz";
      integrity = "sha512-kyCuEOWjJqZuDbRHzL8V93NzQhwIB71oFWSyzVo+KPZI+pnQPPxucdkrOZvkLRnrf5URsQM+IJ09Dw29cRALIA==";
      dependencies = [ "lru-cache@6.0.0" ];
    };

    "human-signals@5.0.0" = {
      pname = "human-signals";
      version = "5.0.0";
      url = "https://registry.npmjs.org/human-signals/-/human-signals-5.0.0.tgz";
      integrity = "sha512-AXcZb6vzzrFAUE61HnN4mpLqd/cSIwNQjtNWR0euPm6y0iqx3G4gOXaIDdtdDwZmhwe82LA6+zinmW4UBWVePQ==";
    };

    "ieee754@1.2.1" = {
      pname = "ieee754";
      version = "1.2.1";
      url = "https://registry.npmjs.org/ieee754/-/ieee754-1.2.1.tgz";
      integrity = "sha512-dcyqhDvX1C46lXZcVqCpK+FtMRQVdIMN6/Df5js2zouUsqG7I6sFxitIC+7KYK29KdXOLHdu9zL4sFnoVQnqaA==";
    };

    "ignore@5.3.2" = {
      pname = "ignore";
      version = "5.3.2";
      url = "https://registry.npmjs.org/ignore/-/ignore-5.3.2.tgz";
      integrity = "sha512-hsBTNUqQTDwkWtcdYI2i06Y/nUBEsNEDJKjWdigLvegy8kDuJAS8uRlpkkcQpyEXL0Z/pjDy5HBmMjRCJ2gq+g==";
    };

    "indent-string@4.0.0" = {
      pname = "indent-string";
      version = "4.0.0";
      url = "https://registry.npmjs.org/indent-string/-/indent-string-4.0.0.tgz";
      integrity = "sha512-EdDDZu4A2OyIK7Lr/2zG+w5jmbuk1DVBnEwREQvBzspBJkCEbRa8GxU1lghYcaGJCnRWibjDXlq779X1/y5xwg==";
    };

    "irregular-plurals@3.5.0" = {
      pname = "irregular-plurals";
      version = "3.5.0";
      url = "https://registry.npmjs.org/irregular-plurals/-/irregular-plurals-3.5.0.tgz";
      integrity = "sha512-1ANGLZ+Nkv1ptFb2pa8oG8Lem4krflKuX/gINiHJHjJUKaJHk/SXk5x6K3J+39/p0h1RQ2saROclJJ+QLvETCQ==";
    };

    "is-arrayish@0.2.1" = {
      pname = "is-arrayish";
      version = "0.2.1";
      url = "https://registry.npmjs.org/is-arrayish/-/is-arrayish-0.2.1.tgz";
      integrity = "sha512-zz06S8t0ozoDXMG+ube26zeCTNXcKIPJZJi8hBrF4idCLms4CG9QtK7qBl1boi5ODzFpjswb5JPmHCbMpjaYzg==";
    };

    "is-core-module@2.16.1" = {
      pname = "is-core-module";
      version = "2.16.1";
      url = "https://registry.npmjs.org/is-core-module/-/is-core-module-2.16.1.tgz";
      integrity = "sha512-UfoeMA6fIJ8wTYFEUjelnaGI67v6+N7qXJEvQuIGa99l4xsCruSYOVSQ0uPANn4dAzm8lkYPaKLrrijLq7x23w==";
      dependencies = [ "hasown@2.0.2" ];
    };

    "is-extglob@2.1.1" = {
      pname = "is-extglob";
      version = "2.1.1";
      url = "https://registry.npmjs.org/is-extglob/-/is-extglob-2.1.1.tgz";
      integrity = "sha512-SbKbANkN603Vi4jEZv49LeVJMn4yGwsbzZworEoyEiutsN3nJYdbO36zfhGJ6QEDpOZIFkDtnq5JRxmvl3jsoQ==";
    };

    "is-fullwidth-code-point@3.0.0" = {
      pname = "is-fullwidth-code-point";
      version = "3.0.0";
      url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-3.0.0.tgz";
      integrity = "sha512-zymm5+u+sCsSWyD9qNaejV3DFvhCKclKdizYaJUuHA83RLjb7nSuGnddCHGv0hk+KY7BMAlsWeK4Ueg6EV6XQg==";
    };

    "is-glob@4.0.3" = {
      pname = "is-glob";
      version = "4.0.3";
      url = "https://registry.npmjs.org/is-glob/-/is-glob-4.0.3.tgz";
      integrity = "sha512-xelSayHH36ZgE7ZWhli7pW34hNbNl8Ojv5KVmkJD4hBdD3th8Tfk9vYasLM+mXWOZhFkgZfxhLSnrwRr4elSSg==";
      dependencies = [ "is-extglob@2.1.1" ];
    };

    "is-number@7.0.0" = {
      pname = "is-number";
      version = "7.0.0";
      url = "https://registry.npmjs.org/is-number/-/is-number-7.0.0.tgz";
      integrity = "sha512-41Cifkg6e8TylSpdtTpeLVMqvSBEVzTttHvERD741+pnZ8ANv0004MRL43QKPDlK9cGvNp6NZWZUBlbGXYxxng==";
    };

    "is-plain-obj@1.1.0" = {
      pname = "is-plain-obj";
      version = "1.1.0";
      url = "https://registry.npmjs.org/is-plain-obj/-/is-plain-obj-1.1.0.tgz";
      integrity = "sha512-yvkRyxmFKEOQ4pNXCmJG5AEQNlXJS5LaONXo5/cLdTZdWvsZ1ioJEonLGAosKlMWE8lwUy/bJzMjcw8az73+Fg==";
    };

    "is-stream@3.0.0" = {
      pname = "is-stream";
      version = "3.0.0";
      url = "https://registry.npmjs.org/is-stream/-/is-stream-3.0.0.tgz";
      integrity = "sha512-LnQR4bZ9IADDRSkvpqMGvt/tEJWclzklNgSw48V5EAaAeDd6qGvN8ei6k5p0tvxSR171VmGyHuTiAOfxAbr8kA==";
    };

    "is-unicode-supported@0.1.0" = {
      pname = "is-unicode-supported";
      version = "0.1.0";
      url = "https://registry.npmjs.org/is-unicode-supported/-/is-unicode-supported-0.1.0.tgz";
      integrity = "sha512-knxG2q4UC3u8stRGyAVJCOdxFmv5DZiRcdlIaAQXAbSfJya+OhopNotLQrstBhququ4ZpuKbDc/8S6mgXgPFPw==";
    };

    "isexe@2.0.0" = {
      pname = "isexe";
      version = "2.0.0";
      url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
      integrity = "sha512-RHxMLp9lnKHGHRng9QFhRCMbYAcVpn69smSGcq3f36xjgVVWThj4qqLbTLlq7Ssj8B+fIQ1EuCEGI2lKsyQeIw==";
    };

    "jest-diff@29.7.0" = {
      pname = "jest-diff";
      version = "29.7.0";
      url = "https://registry.npmjs.org/jest-diff/-/jest-diff-29.7.0.tgz";
      integrity = "sha512-LMIgiIrhigmPrs03JHpxUh2yISK3vLFPkAodPeo0+BuF7wA2FoQbkEg1u8gBYBThncu7e1oEDUfIXVuTqLRUjw==";
      dependencies = [ "chalk@4.1.2" "jest-get-type@29.6.3" "diff-sequences@29.6.3" "pretty-format@29.7.0" ];
    };

    "jest-get-type@29.6.3" = {
      pname = "jest-get-type";
      version = "29.6.3";
      url = "https://registry.npmjs.org/jest-get-type/-/jest-get-type-29.6.3.tgz";
      integrity = "sha512-zrteXnqYxfQh7l5FHyL38jL39di8H8rHoecLH3JNxH3BwOrBsNeabdap5e0I23lD4HHI8W5VFBZqG4Eaq5LNcw==";
    };

    "joycon@3.1.1" = {
      pname = "joycon";
      version = "3.1.1";
      url = "https://registry.npmjs.org/joycon/-/joycon-3.1.1.tgz";
      integrity = "sha512-34wB/Y7MW7bzjKRjUKTa46I2Z7eV62Rkhva+KkopW7Qvv/OSWBqvkSY7vusOPrNuZcUG3tApvdVgNB8POj3SPw==";
    };

    "js-tokens@4.0.0" = {
      pname = "js-tokens";
      version = "4.0.0";
      url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz";
      integrity = "sha512-RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
    };

    "js-tokens@9.0.1" = {
      pname = "js-tokens";
      version = "9.0.1";
      url = "https://registry.npmjs.org/js-tokens/-/js-tokens-9.0.1.tgz";
      integrity = "sha512-mxa9E9ITFOt0ban3j6L5MpjwegGz6lBQmM1IJkWeBZGcMxto50+eWdjC/52xDbS2vy0k7vIMK0Fe2wfL9OQSpQ==";
    };

    "js-yaml@4.1.1" = {
      pname = "js-yaml";
      version = "4.1.1";
      url = "https://registry.npmjs.org/js-yaml/-/js-yaml-4.1.1.tgz";
      integrity = "sha512-qQKT4zQxXl8lLwBtHMWwaTcGfFOZviOJet3Oy/xmGk2gZH677CJM9EvtfdSkgWcATZhj/55JZ0rmy3myCT5lsA==";
      dependencies = [ "argparse@2.0.1" ];
      hasBin = true;
    };

    "json-parse-even-better-errors@2.3.1" = {
      pname = "json-parse-even-better-errors";
      version = "2.3.1";
      url = "https://registry.npmjs.org/json-parse-even-better-errors/-/json-parse-even-better-errors-2.3.1.tgz";
      integrity = "sha512-xyFwyhro/JEof6Ghe2iz2NcXoj2sloNsWr/XsERDK/oiPCfaNhl5ONfp+jQdAZRQQ0IJWNzH9zIZF7li91kh2w==";
    };

    "jsonwebtoken@9.0.2" = {
      pname = "jsonwebtoken";
      version = "9.0.2";
      url = "https://registry.npmjs.org/jsonwebtoken/-/jsonwebtoken-9.0.2.tgz";
      integrity = "sha512-PRp66vJ865SSqOlgqS8hujT5U4AOgMfhrwYIuIhfKaoSCZcirrmASQr8CX7cUg+RMih+hgznrjp99o+W4pJLHQ==";
      dependencies = [ "jws@3.2.2" "lodash.once@4.1.1" "lodash.includes@4.3.0" "lodash.isinteger@4.0.4" "lodash.isnumber@3.0.3" "lodash.isplainobject@4.0.6" "semver@7.7.3" "ms@2.1.3" "lodash.isstring@4.0.1" "lodash.isboolean@3.0.3" ];
    };

    "jwa@1.4.2" = {
      pname = "jwa";
      version = "1.4.2";
      url = "https://registry.npmjs.org/jwa/-/jwa-1.4.2.tgz";
      integrity = "sha512-eeH5JO+21J78qMvTIDdBXidBd6nG2kZjg5Ohz/1fpa28Z4CcsWUzJ1ZZyFq/3z3N17aZy+ZuBoHljASbL1WfOw==";
      dependencies = [ "buffer-equal-constant-time@1.0.1" "ecdsa-sig-formatter@1.0.11" "safe-buffer@5.2.1" ];
    };

    "jws@3.2.2" = {
      pname = "jws";
      version = "3.2.2";
      url = "https://registry.npmjs.org/jws/-/jws-3.2.2.tgz";
      integrity = "sha512-YHlZCB6lMTllWDtSPHz/ZXTsi8S00usEV6v1tjq8tOUZzw7DpSDWVXjXDre6ed1w/pd495ODpHZYSdkRTsa0HA==";
      dependencies = [ "safe-buffer@5.2.1" "jwa@1.4.2" ];
    };

    "kind-of@6.0.3" = {
      pname = "kind-of";
      version = "6.0.3";
      url = "https://registry.npmjs.org/kind-of/-/kind-of-6.0.3.tgz";
      integrity = "sha512-dcS1ul+9tmeD95T+x28/ehLgd9mENa3LsvDTtzm3vyBEO7RPptvAD+t44WVXaUjTBRcrpFeFlC8WCruUR456hw==";
    };

    "lines-and-columns@1.2.4" = {
      pname = "lines-and-columns";
      version = "1.2.4";
      url = "https://registry.npmjs.org/lines-and-columns/-/lines-and-columns-1.2.4.tgz";
      integrity = "sha512-7ylylesZQ/PV29jhEDl3Ufjo6ZX7gCqJr5F7PKrqc93v7fzSymt1BpwEU8nAUXs8qzzvqhbjhK5QZg6Mt/HkBg==";
    };

    "local-pkg@0.5.1" = {
      pname = "local-pkg";
      version = "0.5.1";
      url = "https://registry.npmjs.org/local-pkg/-/local-pkg-0.5.1.tgz";
      integrity = "sha512-9rrA30MRRP3gBD3HTGnC6cDFpaE1kVDWxWgqWJUN0RvDNAo+Nz/9GxB+nHOH0ifbVFy0hSA1V6vFDvnx54lTEQ==";
      dependencies = [ "pkg-types@1.3.1" "mlly@1.8.0" ];
    };

    "locate-path@5.0.0" = {
      pname = "locate-path";
      version = "5.0.0";
      url = "https://registry.npmjs.org/locate-path/-/locate-path-5.0.0.tgz";
      integrity = "sha512-t7hw9pI+WvuwNJXwk5zVHpyhIqzg2qTlklJOf0mVxGSbe3Fp2VieZcduNYjaLDoy6p9uGpQEGWG87WpMKlNq8g==";
      dependencies = [ "p-locate@4.1.0" ];
    };

    "lodash.includes@4.3.0" = {
      pname = "lodash.includes";
      version = "4.3.0";
      url = "https://registry.npmjs.org/lodash.includes/-/lodash.includes-4.3.0.tgz";
      integrity = "sha512-W3Bx6mdkRTGtlJISOvVD/lbqjTlPPUDTMnlXZFnVwi9NKJ6tiAk6LVdlhZMm17VZisqhKcgzpO5Wz91PCt5b0w==";
    };

    "lodash.isboolean@3.0.3" = {
      pname = "lodash.isboolean";
      version = "3.0.3";
      url = "https://registry.npmjs.org/lodash.isboolean/-/lodash.isboolean-3.0.3.tgz";
      integrity = "sha512-Bz5mupy2SVbPHURB98VAcw+aHh4vRV5IPNhILUCsOzRmsTmSQ17jIuqopAentWoehktxGd9e/hbIXq980/1QJg==";
    };

    "lodash.isinteger@4.0.4" = {
      pname = "lodash.isinteger";
      version = "4.0.4";
      url = "https://registry.npmjs.org/lodash.isinteger/-/lodash.isinteger-4.0.4.tgz";
      integrity = "sha512-DBwtEWN2caHQ9/imiNeEA5ys1JoRtRfY3d7V9wkqtbycnAmTvRRmbHKDV4a0EYc678/dia0jrte4tjYwVBaZUA==";
    };

    "lodash.isnumber@3.0.3" = {
      pname = "lodash.isnumber";
      version = "3.0.3";
      url = "https://registry.npmjs.org/lodash.isnumber/-/lodash.isnumber-3.0.3.tgz";
      integrity = "sha512-QYqzpfwO3/CWf3XP+Z+tkQsfaLL/EnUlXWVkIk5FUPc4sBdTehEqZONuyRt2P67PXAk+NXmTBcc97zw9t1FQrw==";
    };

    "lodash.isplainobject@4.0.6" = {
      pname = "lodash.isplainobject";
      version = "4.0.6";
      url = "https://registry.npmjs.org/lodash.isplainobject/-/lodash.isplainobject-4.0.6.tgz";
      integrity = "sha512-oSXzaWypCMHkPC3NvBEaPHf0KsA5mvPrOPgQWDsbg8n7orZ290M0BmC/jgRZ4vcJ6DTAhjrsSYgdsW/F+MFOBA==";
    };

    "lodash.isstring@4.0.1" = {
      pname = "lodash.isstring";
      version = "4.0.1";
      url = "https://registry.npmjs.org/lodash.isstring/-/lodash.isstring-4.0.1.tgz";
      integrity = "sha512-0wJxfxH1wgO3GrbuP+dTTk7op+6L41QCXbGINEmD+ny/G/eCqGzxyCsh7159S+mgDDcoarnBw6PC1PS5+wUGgw==";
    };

    "lodash.once@4.1.1" = {
      pname = "lodash.once";
      version = "4.1.1";
      url = "https://registry.npmjs.org/lodash.once/-/lodash.once-4.1.1.tgz";
      integrity = "sha512-Sb487aTOCr9drQVL8pIxOzVhafOjZN9UU54hiN8PU3uAiSV7lx1yYNpbNmex2PK6dSJoNTSJUUswT651yww3Mg==";
    };

    "log-symbols@4.1.0" = {
      pname = "log-symbols";
      version = "4.1.0";
      url = "https://registry.npmjs.org/log-symbols/-/log-symbols-4.1.0.tgz";
      integrity = "sha512-8XPvpAA8uyhfteu8pIvQxpJZ7SYYdpUivZpGy6sFsBuKRY/7rQGavedeB8aK+Zkyq6upMFVL/9AW6vOYzfRyLg==";
      dependencies = [ "is-unicode-supported@0.1.0" "chalk@4.1.2" ];
    };

    "loupe@2.3.7" = {
      pname = "loupe";
      version = "2.3.7";
      url = "https://registry.npmjs.org/loupe/-/loupe-2.3.7.tgz";
      integrity = "sha512-zSMINGVYkdpYSOBmLi0D1Uo7JU9nVdQKrHxC8eYlV+9YKK9WePqAlL7lSlorG/U2Fw1w0hTBmaa/jrQ3UbPHtA==";
      dependencies = [ "get-func-name@2.0.2" ];
    };

    "lru-cache@6.0.0" = {
      pname = "lru-cache";
      version = "6.0.0";
      url = "https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz";
      integrity = "sha512-Jo6dJ04CmSjuznwJSS3pUeWmd/H0ffTlkXXgwZi+eq1UCmqQwCh+eLsYOYCwY991i2Fah4h1BEMCx4qThGbsiA==";
      dependencies = [ "yallist@4.0.0" ];
    };

    "magic-string@0.30.21" = {
      pname = "magic-string";
      version = "0.30.21";
      url = "https://registry.npmjs.org/magic-string/-/magic-string-0.30.21.tgz";
      integrity = "sha512-vd2F4YUyEXKGcLHoq+TEyCjxueSeHnFxyyjNp80yg0XV4vUhnDer/lvvlqM/arB5bXQN5K2/3oinyCRyx8T2CQ==";
      dependencies = [ "@jridgewell/sourcemap-codec@1.5.5" ];
    };

    "map-obj@1.0.1" = {
      pname = "map-obj";
      version = "1.0.1";
      url = "https://registry.npmjs.org/map-obj/-/map-obj-1.0.1.tgz";
      integrity = "sha512-7N/q3lyZ+LVCp7PzuxrJr4KMbBE2hW7BT7YNia330OFxIf4d3r5zVpicP2650l7CPN6RM9zOJRl3NGpqSiw3Eg==";
    };

    "map-obj@4.3.0" = {
      pname = "map-obj";
      version = "4.3.0";
      url = "https://registry.npmjs.org/map-obj/-/map-obj-4.3.0.tgz";
      integrity = "sha512-hdN1wVrZbb29eBGiGjJbeP8JbKjq1urkHJ/LIP/NY48MZ1QVXUsQBV1G1zvYFHn1XE06cwjBsOI2K3Ulnj1YXQ==";
    };

    "meow@9.0.0" = {
      pname = "meow";
      version = "9.0.0";
      url = "https://registry.npmjs.org/meow/-/meow-9.0.0.tgz";
      integrity = "sha512-+obSblOQmRhcyBt62furQqRAQpNyWXo8BuQ5bN7dG8wmwQ+vwHKp/rCFD4CrTP8CsDQD1sjoZ94K417XEUk8IQ==";
      dependencies = [ "yargs-parser@20.2.9" "trim-newlines@3.0.1" "decamelize-keys@1.1.1" "minimist-options@4.1.0" "@types/minimist@1.2.5" "camelcase-keys@6.2.2" "redent@3.0.0" "type-fest@0.18.1" "hard-rejection@2.1.0" "decamelize@1.2.0" "read-pkg-up@7.0.1" "normalize-package-data@3.0.3" ];
    };

    "merge-stream@2.0.0" = {
      pname = "merge-stream";
      version = "2.0.0";
      url = "https://registry.npmjs.org/merge-stream/-/merge-stream-2.0.0.tgz";
      integrity = "sha512-abv/qOcuPfk3URPfDzmZU1LKmuw8kT+0nIHvKrKgFrwifol/doWcdA4ZqsWQ8ENrFKkd67Mfpo/LovbIUsbt3w==";
    };

    "merge2@1.4.1" = {
      pname = "merge2";
      version = "1.4.1";
      url = "https://registry.npmjs.org/merge2/-/merge2-1.4.1.tgz";
      integrity = "sha512-8q7VEgMJW4J8tcfVPy8g09NcQwZdbwFEqhe/WZkoIzjn/3TGDwtOCYtXGxA3O8tPzpczCCDgv+P2P5y00ZJOOg==";
    };

    "micromatch@4.0.8" = {
      pname = "micromatch";
      version = "4.0.8";
      url = "https://registry.npmjs.org/micromatch/-/micromatch-4.0.8.tgz";
      integrity = "sha512-PXwfBhYu0hBCPw8Dn0E+WDYb7af3dSLVWKi3HGv84IdF4TyFoC0ysxFd0Goxw7nSv4T/PzEJQxsYsEiFCKo2BA==";
      dependencies = [ "braces@3.0.3" "picomatch@2.3.1" ];
    };

    "mimic-fn@4.0.0" = {
      pname = "mimic-fn";
      version = "4.0.0";
      url = "https://registry.npmjs.org/mimic-fn/-/mimic-fn-4.0.0.tgz";
      integrity = "sha512-vqiC06CuhBTUdZH+RYl8sFrL096vA45Ok5ISO6sE/Mr1jRbGH4Csnhi8f3wKVl7x8mO4Au7Ir9D3Oyv1VYMFJw==";
    };

    "min-indent@1.0.1" = {
      pname = "min-indent";
      version = "1.0.1";
      url = "https://registry.npmjs.org/min-indent/-/min-indent-1.0.1.tgz";
      integrity = "sha512-I9jwMn07Sy/IwOj3zVkVik2JTvgpaykDZEigL6Rx6N9LbMywwUSMtxET+7lVoDLLd3O3IXwJwvuuns8UB/HeAg==";
    };

    "minimist-options@4.1.0" = {
      pname = "minimist-options";
      version = "4.1.0";
      url = "https://registry.npmjs.org/minimist-options/-/minimist-options-4.1.0.tgz";
      integrity = "sha512-Q4r8ghd80yhO/0j1O3B2BjweX3fiHg9cdOwjJd2J76Q135c+NDxGCqdYKQ1SKBuFfgWbAUzBfvYjPUEeNgqN1A==";
      dependencies = [ "is-plain-obj@1.1.0" "kind-of@6.0.3" "arrify@1.0.1" ];
    };

    "minimist@1.2.8" = {
      pname = "minimist";
      version = "1.2.8";
      url = "https://registry.npmjs.org/minimist/-/minimist-1.2.8.tgz";
      integrity = "sha512-2yyAR8qBkN3YuheJanUpWC5U3bb5osDywNB8RzDVlDwDHbocAJveqqj1u8+SVD7jkWT4yvsHCpWqqWqAxb0zCA==";
    };

    "mlly@1.8.0" = {
      pname = "mlly";
      version = "1.8.0";
      url = "https://registry.npmjs.org/mlly/-/mlly-1.8.0.tgz";
      integrity = "sha512-l8D9ODSRWLe2KHJSifWGwBqpTZXIXTeo8mlKjY+E2HAakaTeNpqAyBZ8GSqLzHgw4XmHmC8whvpjJNMbFZN7/g==";
      dependencies = [ "pathe@2.0.3" "pkg-types@1.3.1" "ufo@1.6.1" "acorn@8.15.0" ];
    };

    "ms@2.1.3" = {
      pname = "ms";
      version = "2.1.3";
      url = "https://registry.npmjs.org/ms/-/ms-2.1.3.tgz";
      integrity = "sha512-6FlzubTLZG3J2a/NVCAleEhjzq5oxgHyaCU9yYXvcLsvoVaHJq/s5xXI6/XXP6tz7R9xAOtHnSO/tXtF3WRTlA==";
    };

    "nanoid@3.3.11" = {
      pname = "nanoid";
      version = "3.3.11";
      url = "https://registry.npmjs.org/nanoid/-/nanoid-3.3.11.tgz";
      integrity = "sha512-N8SpfPUnUp1bK+PMYW8qSWdl9U+wwNWI4QKxOYDy9JAro3WMX7p2OeVRF9v+347pnakNevPmiHhNmZ2HbFA76w==";
      hasBin = true;
    };

    "normalize-package-data@2.5.0" = {
      pname = "normalize-package-data";
      version = "2.5.0";
      url = "https://registry.npmjs.org/normalize-package-data/-/normalize-package-data-2.5.0.tgz";
      integrity = "sha512-/5CMN3T0R4XTj4DcGaexo+roZSdSFW/0AOOTROrjxzCG1wrWXEsGbRKevjlIL+ZDE4sZlJr5ED4YW0yqmkK+eA==";
      dependencies = [ "resolve@1.22.11" "validate-npm-package-license@3.0.4" "hosted-git-info@2.8.9" ];
    };

    "normalize-package-data@3.0.3" = {
      pname = "normalize-package-data";
      version = "3.0.3";
      url = "https://registry.npmjs.org/normalize-package-data/-/normalize-package-data-3.0.3.tgz";
      integrity = "sha512-p2W1sgqij3zMMyRC067Dg16bfzVH+w7hyegmpIvZ4JNjqtGOVAIvLmjBx3yP7YTe9vKJgkoNOPjwQGogDoMXFA==";
      dependencies = [ "semver@7.7.3" "is-core-module@2.16.1" "validate-npm-package-license@3.0.4" "hosted-git-info@4.1.0" ];
    };

    "npm-run-path@5.3.0" = {
      pname = "npm-run-path";
      version = "5.3.0";
      url = "https://registry.npmjs.org/npm-run-path/-/npm-run-path-5.3.0.tgz";
      integrity = "sha512-ppwTtiJZq0O/ai0z7yfudtBpWIoxM8yE6nHi1X47eFR2EWORqfbu6CnPlNsjeN683eT0qG6H/Pyf9fCcvjnnnQ==";
      dependencies = [ "path-key@4.0.0" ];
    };

    "on-exit-leak-free@2.1.2" = {
      pname = "on-exit-leak-free";
      version = "2.1.2";
      url = "https://registry.npmjs.org/on-exit-leak-free/-/on-exit-leak-free-2.1.2.tgz";
      integrity = "sha512-0eJJY6hXLGf1udHwfNftBqH+g73EU4B504nZeKpz1sYRKafAghwxEJunB2O7rDZkL4PGfsMVnTXZ2EjibbqcsA==";
    };

    "once@1.4.0" = {
      pname = "once";
      version = "1.4.0";
      url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
      integrity = "sha512-lNaJgI+2Q5URQBkccEKHTQOPaXdUxnZZElQTZY0MFUAuaEqe1E+Nyvgdz/aIyNi6Z9MzO5dv1H8n58/GELp3+w==";
      dependencies = [ "wrappy@1.0.2" ];
    };

    "onetime@6.0.0" = {
      pname = "onetime";
      version = "6.0.0";
      url = "https://registry.npmjs.org/onetime/-/onetime-6.0.0.tgz";
      integrity = "sha512-1FlR+gjXK7X+AsAHso35MnyN5KqGwJRi/31ft6x0M194ht7S+rWAvd7PHss9xSKMzE0asv1pyIHaJYq+BbacAQ==";
      dependencies = [ "mimic-fn@4.0.0" ];
    };

    "p-limit@2.3.0" = {
      pname = "p-limit";
      version = "2.3.0";
      url = "https://registry.npmjs.org/p-limit/-/p-limit-2.3.0.tgz";
      integrity = "sha512-//88mFWSJx8lxCzwdAABTJL2MyWB12+eIY7MDL2SqLmAkeKU9qxRvWuSyTjm3FUmpBEMuFfckAIqEaVGUDxb6w==";
      dependencies = [ "p-try@2.2.0" ];
    };

    "p-limit@5.0.0" = {
      pname = "p-limit";
      version = "5.0.0";
      url = "https://registry.npmjs.org/p-limit/-/p-limit-5.0.0.tgz";
      integrity = "sha512-/Eaoq+QyLSiXQ4lyYV23f14mZRQcXnxfHrN0vCai+ak9G0pp9iEQukIIZq5NccEvwRB8PUnZT0KsOoDCINS1qQ==";
      dependencies = [ "yocto-queue@1.2.2" ];
    };

    "p-locate@4.1.0" = {
      pname = "p-locate";
      version = "4.1.0";
      url = "https://registry.npmjs.org/p-locate/-/p-locate-4.1.0.tgz";
      integrity = "sha512-R79ZZ/0wAxKGu3oYMlz8jy/kbhsNrS7SKZ7PxEHBgJ5+F2mtFW2fK2cOtBh1cHYkQsbzFV7I+EoRKe6Yt0oK7A==";
      dependencies = [ "p-limit@2.3.0" ];
    };

    "p-try@2.2.0" = {
      pname = "p-try";
      version = "2.2.0";
      url = "https://registry.npmjs.org/p-try/-/p-try-2.2.0.tgz";
      integrity = "sha512-R4nPAVTAU0B9D35/Gk3uJf/7XYbQcyohSKdvAxIRSNghFl4e71hVoGnBNQz9cWaXxO2I10KTC+3jMdvvoKw6dQ==";
    };

    "parse-json@5.2.0" = {
      pname = "parse-json";
      version = "5.2.0";
      url = "https://registry.npmjs.org/parse-json/-/parse-json-5.2.0.tgz";
      integrity = "sha512-ayCKvm/phCGxOkYRSCM82iDwct8/EonSEgCSxWxD7ve6jHggsFl4fZVQBPRNgQoKiuV/odhFrGzQXZwbifC8Rg==";
      dependencies = [ "json-parse-even-better-errors@2.3.1" "lines-and-columns@1.2.4" "@babel/code-frame@7.27.1" "error-ex@1.3.4" ];
    };

    "path-exists@4.0.0" = {
      pname = "path-exists";
      version = "4.0.0";
      url = "https://registry.npmjs.org/path-exists/-/path-exists-4.0.0.tgz";
      integrity = "sha512-ak9Qy5Q7jYb2Wwcey5Fpvg2KoAc/ZIhLSLOSBmRmygPsGwkVVt0fZa0qrtMz+m6tJTAHfZQ8FnmB4MG4LWy7/w==";
    };

    "path-key@3.1.1" = {
      pname = "path-key";
      version = "3.1.1";
      url = "https://registry.npmjs.org/path-key/-/path-key-3.1.1.tgz";
      integrity = "sha512-ojmeN0qd+y0jszEtoY48r0Peq5dwMEkIlCOu6Q5f41lfkswXuKtYrhgoTpLnyIcHm24Uhqx+5Tqm2InSwLhE6Q==";
    };

    "path-key@4.0.0" = {
      pname = "path-key";
      version = "4.0.0";
      url = "https://registry.npmjs.org/path-key/-/path-key-4.0.0.tgz";
      integrity = "sha512-haREypq7xkM7ErfgIyA0z+Bj4AGKlMSdlQE2jvJo6huWD1EdkKYV+G/T4nq0YEF2vgTT8kqMFKo1uHn950r4SQ==";
    };

    "path-parse@1.0.7" = {
      pname = "path-parse";
      version = "1.0.7";
      url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.7.tgz";
      integrity = "sha512-LDJzPVEEEPR+y48z93A0Ed0yXb8pAByGWo/k5YYdYgpY2/2EsOsksJrq7lOHxryrVOn1ejG6oAp8ahvOIQD8sw==";
    };

    "path-type@4.0.0" = {
      pname = "path-type";
      version = "4.0.0";
      url = "https://registry.npmjs.org/path-type/-/path-type-4.0.0.tgz";
      integrity = "sha512-gDKb8aZMDeD/tZWs9P6+q0J9Mwkdl6xMV8TjnGP3qJVJ06bdMgkbBlLU8IdfOsIsFz2BW1rNVT3XuNEl8zPAvw==";
    };

    "pathe@1.1.2" = {
      pname = "pathe";
      version = "1.1.2";
      url = "https://registry.npmjs.org/pathe/-/pathe-1.1.2.tgz";
      integrity = "sha512-whLdWMYL2TwI08hn8/ZqAbrVemu0LNaNNJZX73O6qaIdCTfXutsLhMkjdENX0qhsQ9uIimo4/aQOmXkoon2nDQ==";
    };

    "pathe@2.0.3" = {
      pname = "pathe";
      version = "2.0.3";
      url = "https://registry.npmjs.org/pathe/-/pathe-2.0.3.tgz";
      integrity = "sha512-WUjGcAqP1gQacoQe+OBJsFA7Ld4DyXuUIjZ5cc75cLHvJ7dtNsTugphxIADwspS+AraAUePCKrSVtPLFj/F88w==";
    };

    "pathval@1.1.1" = {
      pname = "pathval";
      version = "1.1.1";
      url = "https://registry.npmjs.org/pathval/-/pathval-1.1.1.tgz";
      integrity = "sha512-Dp6zGqpTdETdR63lehJYPeIOqpiNBNtc7BpWSLrOje7UaIsE5aY92r/AunQA7rsXvet3lrJ3JnZX29UPTKXyKQ==";
    };

    "picocolors@1.1.1" = {
      pname = "picocolors";
      version = "1.1.1";
      url = "https://registry.npmjs.org/picocolors/-/picocolors-1.1.1.tgz";
      integrity = "sha512-xceH2snhtb5M9liqDsmEw56le376mTZkEX/jEb/RxNFyegNul7eNslCXP9FDj/Lcu0X8KEyMceP2ntpaHrDEVA==";
    };

    "picomatch@2.3.1" = {
      pname = "picomatch";
      version = "2.3.1";
      url = "https://registry.npmjs.org/picomatch/-/picomatch-2.3.1.tgz";
      integrity = "sha512-JU3teHTNjmE2VCGFzuY8EXzCDVwEqB2a8fsIvwaStHhAWJEeVd1o1QD80CU6+ZdEXXSLbSsuLwJjkCBWqRQUVA==";
    };

    "pino-abstract-transport@1.2.0" = {
      pname = "pino-abstract-transport";
      version = "1.2.0";
      url = "https://registry.npmjs.org/pino-abstract-transport/-/pino-abstract-transport-1.2.0.tgz";
      integrity = "sha512-Guhh8EZfPCfH+PMXAb6rKOjGQEoy0xlAIn+irODG5kgfYV+BQ0rGYYWTIel3P5mmyXqkYkPmdIkywsn6QKUR1Q==";
      dependencies = [ "split2@4.2.0" "readable-stream@4.7.0" ];
    };

    "pino-pretty@10.3.1" = {
      pname = "pino-pretty";
      version = "10.3.1";
      url = "https://registry.npmjs.org/pino-pretty/-/pino-pretty-10.3.1.tgz";
      integrity = "sha512-az8JbIYeN/1iLj2t0jR9DV48/LQ3RC6hZPpapKPkb84Q+yTidMCpgWxIT3N0flnBDilyBQ1luWNpOeJptjdp/g==";
      dependencies = [ "pump@3.0.3" "minimist@1.2.8" "secure-json-parse@2.7.0" "readable-stream@4.7.0" "on-exit-leak-free@2.1.2" "pino-abstract-transport@1.2.0" "fast-safe-stringify@2.1.1" "joycon@3.1.1" "help-me@5.0.0" "colorette@2.0.20" "dateformat@4.6.3" "sonic-boom@3.8.1" "fast-copy@3.0.2" "strip-json-comments@3.1.1" ];
      hasBin = true;
    };

    "pino-std-serializers@6.2.2" = {
      pname = "pino-std-serializers";
      version = "6.2.2";
      url = "https://registry.npmjs.org/pino-std-serializers/-/pino-std-serializers-6.2.2.tgz";
      integrity = "sha512-cHjPPsE+vhj/tnhCy/wiMh3M3z3h/j15zHQX+S9GkTBgqJuTuJzYJ4gUyACLhDaJ7kk9ba9iRDmbH2tJU03OiA==";
    };

    "pino@8.21.0" = {
      pname = "pino";
      version = "8.21.0";
      url = "https://registry.npmjs.org/pino/-/pino-8.21.0.tgz";
      integrity = "sha512-ip4qdzjkAyDDZklUaZkcRFb2iA118H9SgRh8yzTkSQK8HilsOJF7rSY8HoW5+I0M46AZgX/pxbprf2vvzQCE0Q==";
      dependencies = [ "sonic-boom@3.8.1" "safe-stable-stringify@2.5.0" "process-warning@3.0.0" "pino-abstract-transport@1.2.0" "quick-format-unescaped@4.0.4" "real-require@0.2.0" "on-exit-leak-free@2.1.2" "thread-stream@2.7.0" "atomic-sleep@1.0.0" "pino-std-serializers@6.2.2" "fast-redact@3.5.0" ];
      hasBin = true;
    };

    "pkg-types@1.3.1" = {
      pname = "pkg-types";
      version = "1.3.1";
      url = "https://registry.npmjs.org/pkg-types/-/pkg-types-1.3.1.tgz";
      integrity = "sha512-/Jm5M4RvtBFVkKWRu2BLUTNP8/M2a+UwuAX+ae4770q1qVGtfjG+WTCupoZixokjmHiry8uI+dlY8KXYV5HVVQ==";
      dependencies = [ "pathe@2.0.3" "confbox@0.1.8" "mlly@1.8.0" ];
    };

    "plur@4.0.0" = {
      pname = "plur";
      version = "4.0.0";
      url = "https://registry.npmjs.org/plur/-/plur-4.0.0.tgz";
      integrity = "sha512-4UGewrYgqDFw9vV6zNV+ADmPAUAfJPKtGvb/VdpQAx25X5f3xXdGdyOEVFwkl8Hl/tl7+xbeHqSEM+D5/TirUg==";
      dependencies = [ "irregular-plurals@3.5.0" ];
    };

    "postcss@8.5.6" = {
      pname = "postcss";
      version = "8.5.6";
      url = "https://registry.npmjs.org/postcss/-/postcss-8.5.6.tgz";
      integrity = "sha512-3Ybi1tAuwAP9s0r1UQ2J4n5Y0G05bJkpUIO0/bI9MhwmD70S5aTWbXGBwxHrelT+XM1k6dM0pk+SwNkpTRN7Pg==";
      dependencies = [ "nanoid@3.3.11" "picocolors@1.1.1" "source-map-js@1.2.1" ];
    };

    "pretty-format@29.7.0" = {
      pname = "pretty-format";
      version = "29.7.0";
      url = "https://registry.npmjs.org/pretty-format/-/pretty-format-29.7.0.tgz";
      integrity = "sha512-Pdlw/oPxN+aXdmM9R00JVC9WVFoCLTKJvDVLgmJ+qAffBMxsV85l/Lu7sNx4zSzPyoL2euImuEwHhOXdEgNFZQ==";
      dependencies = [ "ansi-styles@5.2.0" "react-is@18.3.1" "@jest/schemas@29.6.3" ];
    };

    "process-warning@3.0.0" = {
      pname = "process-warning";
      version = "3.0.0";
      url = "https://registry.npmjs.org/process-warning/-/process-warning-3.0.0.tgz";
      integrity = "sha512-mqn0kFRl0EoqhnL0GQ0veqFHyIN1yig9RHh/InzORTUiZHFRAur+aMtRkELNwGs9aNwKS6tg/An4NYBPGwvtzQ==";
    };

    "process@0.11.10" = {
      pname = "process";
      version = "0.11.10";
      url = "https://registry.npmjs.org/process/-/process-0.11.10.tgz";
      integrity = "sha512-cdGef/drWFoydD1JsMzuFf8100nZl+GT+yacc2bEced5f9Rjk4z+WtFUTBu9PhOi9j/jfmBPu0mMEY4wIdAF8A==";
    };

    "pump@3.0.3" = {
      pname = "pump";
      version = "3.0.3";
      url = "https://registry.npmjs.org/pump/-/pump-3.0.3.tgz";
      integrity = "sha512-todwxLMY7/heScKmntwQG8CXVkWUOdYxIvY2s0VWAAMh/nd8SoYiRaKjlr7+iCs984f2P8zvrfWcDDYVb73NfA==";
      dependencies = [ "once@1.4.0" "end-of-stream@1.4.5" ];
    };

    "queue-microtask@1.2.3" = {
      pname = "queue-microtask";
      version = "1.2.3";
      url = "https://registry.npmjs.org/queue-microtask/-/queue-microtask-1.2.3.tgz";
      integrity = "sha512-NuaNSa6flKT5JaSYQzJok04JzTL1CA6aGhv5rfLW3PgqA+M2ChpZQnAC8h8i4ZFkBS8X5RqkDBHA7r4hej3K9A==";
    };

    "quick-format-unescaped@4.0.4" = {
      pname = "quick-format-unescaped";
      version = "4.0.4";
      url = "https://registry.npmjs.org/quick-format-unescaped/-/quick-format-unescaped-4.0.4.tgz";
      integrity = "sha512-tYC1Q1hgyRuHgloV/YXs2w15unPVh8qfu/qCTfhTYamaw7fyhumKa2yGpdSo87vY32rIclj+4fWYQXUMs9EHvg==";
    };

    "quick-lru@4.0.1" = {
      pname = "quick-lru";
      version = "4.0.1";
      url = "https://registry.npmjs.org/quick-lru/-/quick-lru-4.0.1.tgz";
      integrity = "sha512-ARhCpm70fzdcvNQfPoy49IaanKkTlRWF2JMzqhcJbhSFRZv7nPTvZJdcY7301IPmvW+/p0RgIWnQDLJxifsQ7g==";
    };

    "react-is@18.3.1" = {
      pname = "react-is";
      version = "18.3.1";
      url = "https://registry.npmjs.org/react-is/-/react-is-18.3.1.tgz";
      integrity = "sha512-/LLMVyas0ljjAtoYiPqYiL8VWXzUUdThrmU5+n20DZv+a+ClRoevUzw5JxU+Ieh5/c87ytoTBV9G1FiKfNJdmg==";
    };

    "read-pkg-up@7.0.1" = {
      pname = "read-pkg-up";
      version = "7.0.1";
      url = "https://registry.npmjs.org/read-pkg-up/-/read-pkg-up-7.0.1.tgz";
      integrity = "sha512-zK0TB7Xd6JpCLmlLmufqykGE+/TlOePD6qKClNW7hHDKFh/J7/7gCWGR7joEQEW1bKq3a3yUZSObOoWLFQ4ohg==";
      dependencies = [ "type-fest@0.8.1" "find-up@4.1.0" "read-pkg@5.2.0" ];
    };

    "read-pkg@5.2.0" = {
      pname = "read-pkg";
      version = "5.2.0";
      url = "https://registry.npmjs.org/read-pkg/-/read-pkg-5.2.0.tgz";
      integrity = "sha512-Ug69mNOpfvKDAc2Q8DRpMjjzdtrnv9HcSMX+4VsZxD1aZ6ZzrIE7rlzXBtWTyhULSMKg076AW6WR5iZpD0JiOg==";
      dependencies = [ "normalize-package-data@2.5.0" "parse-json@5.2.0" "type-fest@0.6.0" "@types/normalize-package-data@2.4.4" ];
    };

    "readable-stream@4.7.0" = {
      pname = "readable-stream";
      version = "4.7.0";
      url = "https://registry.npmjs.org/readable-stream/-/readable-stream-4.7.0.tgz";
      integrity = "sha512-oIGGmcpTLwPga8Bn6/Z75SVaH1z5dUut2ibSyAMVhmUggWpmDn2dapB0n7f8nwaSiRtepAsfJyfXIO5DCVAODg==";
      dependencies = [ "abort-controller@3.0.0" "buffer@6.0.3" "events@3.3.0" "process@0.11.10" "string_decoder@1.3.0" ];
    };

    "real-require@0.2.0" = {
      pname = "real-require";
      version = "0.2.0";
      url = "https://registry.npmjs.org/real-require/-/real-require-0.2.0.tgz";
      integrity = "sha512-57frrGM/OCTLqLOAh0mhVA9VBMHd+9U7Zb2THMGdBUoZVOtGbJzjxsYGDJ3A9AYYCP4hn6y1TVbaOfzWtm5GFg==";
    };

    "redent@3.0.0" = {
      pname = "redent";
      version = "3.0.0";
      url = "https://registry.npmjs.org/redent/-/redent-3.0.0.tgz";
      integrity = "sha512-6tDA8g98We0zd0GvVeMT9arEOnTw9qM03L9cJXaCjrip1OO764RDBLBfrB4cwzNGDj5OA5ioymC9GkizgWJDUg==";
      dependencies = [ "strip-indent@3.0.0" "indent-string@4.0.0" ];
    };

    "resolve@1.22.11" = {
      pname = "resolve";
      version = "1.22.11";
      url = "https://registry.npmjs.org/resolve/-/resolve-1.22.11.tgz";
      integrity = "sha512-RfqAvLnMl313r7c9oclB1HhUEAezcpLjz95wFH4LVuhk9JF/r22qmVP9AMmOU4vMX7Q8pN8jwNg/CSpdFnMjTQ==";
      dependencies = [ "is-core-module@2.16.1" "path-parse@1.0.7" "supports-preserve-symlinks-flag@1.0.0" ];
      hasBin = true;
    };

    "reusify@1.1.0" = {
      pname = "reusify";
      version = "1.1.0";
      url = "https://registry.npmjs.org/reusify/-/reusify-1.1.0.tgz";
      integrity = "sha512-g6QUff04oZpHs0eG5p83rFLhHeV00ug/Yf9nZM6fLeUrPguBTkTQOdpAWWspMh55TZfVQDPaN3NQJfbVRAxdIw==";
    };

    "rollup@4.53.3" = {
      pname = "rollup";
      version = "4.53.3";
      url = "https://registry.npmjs.org/rollup/-/rollup-4.53.3.tgz";
      integrity = "sha512-w8GmOxZfBmKknvdXU1sdM9NHcoQejwF/4mNgj2JuEEdRaHwwF12K7e9eXn1nLZ07ad+du76mkVsyeb2rKGllsA==";
      dependencies = [ "@types/estree@1.0.8" "@rollup/rollup-linux-arm-musleabihf@4.53.3" "@rollup/rollup-linux-ppc64-gnu@4.53.3" "@rollup/rollup-linux-x64-musl@4.53.3" "@rollup/rollup-linux-riscv64-gnu@4.53.3" "@rollup/rollup-linux-s390x-gnu@4.53.3" "@rollup/rollup-linux-arm-gnueabihf@4.53.3" "@rollup/rollup-linux-riscv64-musl@4.53.3" "@rollup/rollup-linux-x64-gnu@4.53.3" "@rollup/rollup-linux-arm64-musl@4.53.3" "@rollup/rollup-linux-arm64-gnu@4.53.3" "@rollup/rollup-linux-loong64-gnu@4.53.3" ];
      hasBin = true;
    };

    "run-parallel@1.2.0" = {
      pname = "run-parallel";
      version = "1.2.0";
      url = "https://registry.npmjs.org/run-parallel/-/run-parallel-1.2.0.tgz";
      integrity = "sha512-5l4VyZR86LZ/lDxZTR6jqL8AFE2S0IFLMP26AbjsLVADxHdhB/c0GUsH+y39UfCi3dzz8OlQuPmnaJOMoDHQBA==";
      dependencies = [ "queue-microtask@1.2.3" ];
    };

    "safe-buffer@5.2.1" = {
      pname = "safe-buffer";
      version = "5.2.1";
      url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
      integrity = "sha512-rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
    };

    "safe-stable-stringify@2.5.0" = {
      pname = "safe-stable-stringify";
      version = "2.5.0";
      url = "https://registry.npmjs.org/safe-stable-stringify/-/safe-stable-stringify-2.5.0.tgz";
      integrity = "sha512-b3rppTKm9T+PsVCBEOUR46GWI7fdOs00VKZ1+9c1EWDaDMvjQc6tUwuFyIprgGgTcWoVHSKrU8H31ZHA2e0RHA==";
    };

    "secure-json-parse@2.7.0" = {
      pname = "secure-json-parse";
      version = "2.7.0";
      url = "https://registry.npmjs.org/secure-json-parse/-/secure-json-parse-2.7.0.tgz";
      integrity = "sha512-6aU+Rwsezw7VR8/nyvKTx8QpWH9FrcYiXXlqC4z5d5XQBDRqtbfsRjnwGyqbi3gddNtWHuEk9OANUotL26qKUw==";
    };

    "semver@2.3.2" = {
      pname = "semver";
      version = "2.3.2";
      url = "https://registry.npmjs.org/semver/-/semver-2.3.2.tgz";
      integrity = "sha512-abLdIKCosKfpnmhS52NCTjO4RiLspDfsn37prjzGrp9im5DPJOgh82Os92vtwGh6XdQryKI/7SREZnV+aqiXrA==";
      hasBin = true;
    };

    "semver@7.7.3" = {
      pname = "semver";
      version = "7.7.3";
      url = "https://registry.npmjs.org/semver/-/semver-7.7.3.tgz";
      integrity = "sha512-SdsKMrI9TdgjdweUSR9MweHA4EJ8YxHn8DFaDisvhVlUOe4BF1tLD7GAj0lIqWVl+dPb/rExr0Btby5loQm20Q==";
      hasBin = true;
    };

    "shebang-command@2.0.0" = {
      pname = "shebang-command";
      version = "2.0.0";
      url = "https://registry.npmjs.org/shebang-command/-/shebang-command-2.0.0.tgz";
      integrity = "sha512-kHxr2zZpYtdmrN1qDjrrX/Z1rR1kG8Dx+gkpK1G4eXmvXswmcE1hTWBWYUzlraYw1/yZp6YuDY77YtvbN0dmDA==";
      dependencies = [ "shebang-regex@3.0.0" ];
    };

    "shebang-regex@3.0.0" = {
      pname = "shebang-regex";
      version = "3.0.0";
      url = "https://registry.npmjs.org/shebang-regex/-/shebang-regex-3.0.0.tgz";
      integrity = "sha512-7++dFhtcx3353uBaq8DDR4NuxBetBzC7ZQOhmTQInHEd6bSrXdiEyzCvG07Z44UYdLShWUyXt5M/yhz8ekcb1A==";
    };

    "siginfo@2.0.0" = {
      pname = "siginfo";
      version = "2.0.0";
      url = "https://registry.npmjs.org/siginfo/-/siginfo-2.0.0.tgz";
      integrity = "sha512-ybx0WO1/8bSBLEWXZvEd7gMW3Sn3JFlW3TvX1nREbDLRNQNaeNN8WK0meBwPdAaOI7TtRRRJn/Es1zhrrCHu7g==";
    };

    "signal-exit@4.1.0" = {
      pname = "signal-exit";
      version = "4.1.0";
      url = "https://registry.npmjs.org/signal-exit/-/signal-exit-4.1.0.tgz";
      integrity = "sha512-bzyZ1e88w9O1iNJbKnOlvYTrWPDl46O1bG0D3XInv+9tkPrxrN8jUUTiFlDkkmKWgn1M6CfIA13SuGqOa9Korw==";
    };

    "slash@3.0.0" = {
      pname = "slash";
      version = "3.0.0";
      url = "https://registry.npmjs.org/slash/-/slash-3.0.0.tgz";
      integrity = "sha512-g9Q1haeby36OSStwb4ntCGGGaKsaVSjQ68fBxoQcutl5fS1vuY18H3wSt3jFyFtrkx+Kz0V1G85A4MyAdDMi2Q==";
    };

    "sonic-boom@3.8.1" = {
      pname = "sonic-boom";
      version = "3.8.1";
      url = "https://registry.npmjs.org/sonic-boom/-/sonic-boom-3.8.1.tgz";
      integrity = "sha512-y4Z8LCDBuum+PBP3lSV7RHrXscqksve/bi0as7mhwVnBW+/wUqKT/2Kb7um8yqcFy0duYbbPxzt89Zy2nOCaxg==";
      dependencies = [ "atomic-sleep@1.0.0" ];
    };

    "source-map-js@1.2.1" = {
      pname = "source-map-js";
      version = "1.2.1";
      url = "https://registry.npmjs.org/source-map-js/-/source-map-js-1.2.1.tgz";
      integrity = "sha512-UXWMKhLOwVKb728IUtQPXxfYU+usdybtUrK/8uGE8CQMvrhOpwvzDBwj0QhSL7MQc7vIsISBG8VQ8+IDQxpfQA==";
    };

    "spdx-correct@3.2.0" = {
      pname = "spdx-correct";
      version = "3.2.0";
      url = "https://registry.npmjs.org/spdx-correct/-/spdx-correct-3.2.0.tgz";
      integrity = "sha512-kN9dJbvnySHULIluDHy32WHRUu3Og7B9sbY7tsFLctQkIqnMh3hErYgdMjTYuqmcXX+lK5T1lnUt3G7zNswmZA==";
      dependencies = [ "spdx-expression-parse@3.0.1" "spdx-license-ids@3.0.22" ];
    };

    "spdx-exceptions@2.5.0" = {
      pname = "spdx-exceptions";
      version = "2.5.0";
      url = "https://registry.npmjs.org/spdx-exceptions/-/spdx-exceptions-2.5.0.tgz";
      integrity = "sha512-PiU42r+xO4UbUS1buo3LPJkjlO7430Xn5SVAhdpzzsPHsjbYVflnnFdATgabnLude+Cqu25p6N+g2lw/PFsa4w==";
    };

    "spdx-expression-parse@3.0.1" = {
      pname = "spdx-expression-parse";
      version = "3.0.1";
      url = "https://registry.npmjs.org/spdx-expression-parse/-/spdx-expression-parse-3.0.1.tgz";
      integrity = "sha512-cbqHunsQWnJNE6KhVSMsMeH5H/L9EpymbzqTQ3uLwNCLZ1Q481oWaofqH7nO6V07xlXwY6PhQdQ2IedWx/ZK4Q==";
      dependencies = [ "spdx-license-ids@3.0.22" "spdx-exceptions@2.5.0" ];
    };

    "spdx-license-ids@3.0.22" = {
      pname = "spdx-license-ids";
      version = "3.0.22";
      url = "https://registry.npmjs.org/spdx-license-ids/-/spdx-license-ids-3.0.22.tgz";
      integrity = "sha512-4PRT4nh1EImPbt2jASOKHX7PB7I+e4IWNLvkKFDxNhJlfjbYlleYQh285Z/3mPTHSAK/AvdMmw5BNNuYH8ShgQ==";
    };

    "split2@4.2.0" = {
      pname = "split2";
      version = "4.2.0";
      url = "https://registry.npmjs.org/split2/-/split2-4.2.0.tgz";
      integrity = "sha512-UcjcJOWknrNkF6PLX83qcHM6KHgVKNkV62Y8a5uYDVv9ydGQVwAHMKqHdJje1VTWpljG0WYpCDhrCdAOYH4TWg==";
    };

    "stackback@0.0.2" = {
      pname = "stackback";
      version = "0.0.2";
      url = "https://registry.npmjs.org/stackback/-/stackback-0.0.2.tgz";
      integrity = "sha512-1XMJE5fQo1jGH6Y/7ebnwPOBEkIEnT4QF32d5R1+VXdXveM0IBMJt8zfaxX1P3QhVwrYe+576+jkANtSS2mBbw==";
    };

    "std-env@3.10.0" = {
      pname = "std-env";
      version = "3.10.0";
      url = "https://registry.npmjs.org/std-env/-/std-env-3.10.0.tgz";
      integrity = "sha512-5GS12FdOZNliM5mAOxFRg7Ir0pWz8MdpYm6AY6VPkGpbA7ZzmbzNcBJQ0GPvvyWgcY7QAhCgf9Uy89I03faLkg==";
    };

    "string-width@4.2.3" = {
      pname = "string-width";
      version = "4.2.3";
      url = "https://registry.npmjs.org/string-width/-/string-width-4.2.3.tgz";
      integrity = "sha512-wKyQRQpjJ0sIp62ErSZdGsjMJWsap5oRNihHhu6G7JVO/9jIB6UyevL+tXuOqrng8j/cxKTWyWUwvSTriiZz/g==";
      dependencies = [ "emoji-regex@8.0.0" "is-fullwidth-code-point@3.0.0" "strip-ansi@6.0.1" ];
    };

    "string_decoder@1.3.0" = {
      pname = "string_decoder";
      version = "1.3.0";
      url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.3.0.tgz";
      integrity = "sha512-hkRX8U1WjJFd8LsDJ2yQ/wWWxaopEsABU1XfkM8A+j0+85JAGppt16cr1Whg6KIbb4okU6Mql6BOj+uup/wKeA==";
      dependencies = [ "safe-buffer@5.2.1" ];
    };

    "strip-ansi@6.0.1" = {
      pname = "strip-ansi";
      version = "6.0.1";
      url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.1.tgz";
      integrity = "sha512-Y38VPSHcqkFrCpFnQ9vuSXmquuv5oXOKpGeT6aGrr3o3Gc9AlVa6JBfUSOCnbxGGZF+/0ooI7KrPuUSztUdU5A==";
      dependencies = [ "ansi-regex@5.0.1" ];
    };

    "strip-final-newline@3.0.0" = {
      pname = "strip-final-newline";
      version = "3.0.0";
      url = "https://registry.npmjs.org/strip-final-newline/-/strip-final-newline-3.0.0.tgz";
      integrity = "sha512-dOESqjYr96iWYylGObzd39EuNTa5VJxyvVAEm5Jnh7KGo75V43Hk1odPQkNDyXNmUR6k+gEiDVXnjB8HJ3crXw==";
    };

    "strip-indent@3.0.0" = {
      pname = "strip-indent";
      version = "3.0.0";
      url = "https://registry.npmjs.org/strip-indent/-/strip-indent-3.0.0.tgz";
      integrity = "sha512-laJTa3Jb+VQpaC6DseHhF7dXVqHTfJPCRDaEbid/drOhgitgYku/letMUqOXFoWV0zIIUbjpdH2t+tYj4bQMRQ==";
      dependencies = [ "min-indent@1.0.1" ];
    };

    "strip-json-comments@3.1.1" = {
      pname = "strip-json-comments";
      version = "3.1.1";
      url = "https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-3.1.1.tgz";
      integrity = "sha512-6fPc+R4ihwqP6N/aIv2f1gMH8lOVtWQHoqC4yK6oSDVVocumAsfCqjkXnqiYMhmMwS/mEHLp7Vehlt3ql6lEig==";
    };

    "strip-literal@2.1.1" = {
      pname = "strip-literal";
      version = "2.1.1";
      url = "https://registry.npmjs.org/strip-literal/-/strip-literal-2.1.1.tgz";
      integrity = "sha512-631UJ6O00eNGfMiWG78ck80dfBab8X6IVFB51jZK5Icd7XAs60Z5y7QdSd/wGIklnWvRbUNloVzhOKKmutxQ6Q==";
      dependencies = [ "js-tokens@9.0.1" ];
    };

    "supports-color@7.2.0" = {
      pname = "supports-color";
      version = "7.2.0";
      url = "https://registry.npmjs.org/supports-color/-/supports-color-7.2.0.tgz";
      integrity = "sha512-qpCAvRl9stuOHveKsn7HncJRvv501qIacKzQlO/+Lwxc9+0q2wLyv4Dfvt80/DPn2pqOBsJdDiogXGR9+OvwRw==";
      dependencies = [ "has-flag@4.0.0" ];
    };

    "supports-hyperlinks@2.3.0" = {
      pname = "supports-hyperlinks";
      version = "2.3.0";
      url = "https://registry.npmjs.org/supports-hyperlinks/-/supports-hyperlinks-2.3.0.tgz";
      integrity = "sha512-RpsAZlpWcDwOPQA22aCH4J0t7L8JmAvsCxfOSEwm7cQs3LshN36QaTkwd70DnBOXDWGssw2eUoc8CaRWT0XunA==";
      dependencies = [ "has-flag@4.0.0" "supports-color@7.2.0" ];
    };

    "supports-preserve-symlinks-flag@1.0.0" = {
      pname = "supports-preserve-symlinks-flag";
      version = "1.0.0";
      url = "https://registry.npmjs.org/supports-preserve-symlinks-flag/-/supports-preserve-symlinks-flag-1.0.0.tgz";
      integrity = "sha512-ot0WnXS9fgdkgIcePe6RHNk1WA8+muPa6cSjeR3V8K27q9BB1rTE3R1p7Hv0z1ZyAc8s6Vvv8DIyWf681MAt0w==";
    };

    "thread-stream@2.7.0" = {
      pname = "thread-stream";
      version = "2.7.0";
      url = "https://registry.npmjs.org/thread-stream/-/thread-stream-2.7.0.tgz";
      integrity = "sha512-qQiRWsU/wvNolI6tbbCKd9iKaTnCXsTwVxhhKM6nctPdujTyztjlbUkUTUymidWcMnZ5pWR0ej4a0tjsW021vw==";
      dependencies = [ "real-require@0.2.0" ];
    };

    "tinybench@2.9.0" = {
      pname = "tinybench";
      version = "2.9.0";
      url = "https://registry.npmjs.org/tinybench/-/tinybench-2.9.0.tgz";
      integrity = "sha512-0+DUvqWMValLmha6lr4kD8iAMK1HzV0/aKnCtWb9v9641TnP/MFb7Pc2bxoxQjTXAErryXVgUOfv2YqNllqGeg==";
    };

    "tinypool@0.8.4" = {
      pname = "tinypool";
      version = "0.8.4";
      url = "https://registry.npmjs.org/tinypool/-/tinypool-0.8.4.tgz";
      integrity = "sha512-i11VH5gS6IFeLY3gMBQ00/MmLncVP7JLXOw1vlgkytLmJK7QnEr7NXf0LBdxfmNPAeyetukOk0bOYrJrFGjYJQ==";
    };

    "tinyspy@2.2.1" = {
      pname = "tinyspy";
      version = "2.2.1";
      url = "https://registry.npmjs.org/tinyspy/-/tinyspy-2.2.1.tgz";
      integrity = "sha512-KYad6Vy5VDWV4GH3fjpseMQ/XU2BhIYP7Vzd0LG44qRWm/Yt2WCOTicFdvmgo6gWaqooMQCawTtILVQJupKu7A==";
    };

    "to-regex-range@5.0.1" = {
      pname = "to-regex-range";
      version = "5.0.1";
      url = "https://registry.npmjs.org/to-regex-range/-/to-regex-range-5.0.1.tgz";
      integrity = "sha512-65P7iz6X5yEr1cwcgvQxbbIw7Uk3gOy5dIdtZ4rDveLqhrdJP+Li/Hx6tyK0NEb+2GCyneCMJiGqrADCSNk8sQ==";
      dependencies = [ "is-number@7.0.0" ];
    };

    "trim-newlines@3.0.1" = {
      pname = "trim-newlines";
      version = "3.0.1";
      url = "https://registry.npmjs.org/trim-newlines/-/trim-newlines-3.0.1.tgz";
      integrity = "sha512-c1PTsA3tYrIsLGkJkzHF+w9F2EyxfXGo4UyJc4pFL++FMjnq0HJS69T3M7d//gKrFKwy429bouPescbjecU+Zw==";
    };

    "tsd@0.29.0" = {
      pname = "tsd";
      version = "0.29.0";
      url = "https://registry.npmjs.org/tsd/-/tsd-0.29.0.tgz";
      integrity = "sha512-5B7jbTj+XLMg6rb9sXRBGwzv7h8KJlGOkTHxY63eWpZJiQ5vJbXEjL0u7JkIxwi5EsrRE1kRVUWmy6buK/ii8A==";
      dependencies = [ "read-pkg-up@7.0.1" "globby@11.1.0" "@tsd/typescript@5.2.2" "meow@9.0.0" "jest-diff@29.7.0" "path-exists@4.0.0" "eslint-formatter-pretty@4.1.0" ];
      hasBin = true;
    };

    "type-detect@4.1.0" = {
      pname = "type-detect";
      version = "4.1.0";
      url = "https://registry.npmjs.org/type-detect/-/type-detect-4.1.0.tgz";
      integrity = "sha512-Acylog8/luQ8L7il+geoSxhEkazvkslg7PSNKOX59mbB9cOveP5aq9h74Y7YU8yDpJwetzQQrfIwtf4Wp4LKcw==";
    };

    "type-fest@0.18.1" = {
      pname = "type-fest";
      version = "0.18.1";
      url = "https://registry.npmjs.org/type-fest/-/type-fest-0.18.1.tgz";
      integrity = "sha512-OIAYXk8+ISY+qTOwkHtKqzAuxchoMiD9Udx+FSGQDuiRR+PJKJHc2NJAXlbhkGwTt/4/nKZxELY1w3ReWOL8mw==";
    };

    "type-fest@0.21.3" = {
      pname = "type-fest";
      version = "0.21.3";
      url = "https://registry.npmjs.org/type-fest/-/type-fest-0.21.3.tgz";
      integrity = "sha512-t0rzBq87m3fVcduHDUFhKmyyX+9eo6WQjZvf51Ea/M0Q7+T374Jp1aUiyUl0GKxp8M/OETVHSDvmkyPgvX+X2w==";
    };

    "type-fest@0.6.0" = {
      pname = "type-fest";
      version = "0.6.0";
      url = "https://registry.npmjs.org/type-fest/-/type-fest-0.6.0.tgz";
      integrity = "sha512-q+MB8nYR1KDLrgr4G5yemftpMC7/QLqVndBmEEdqzmNj5dcFOO4Oo8qlwZE3ULT3+Zim1F8Kq4cBnikNhlCMlg==";
    };

    "type-fest@0.8.1" = {
      pname = "type-fest";
      version = "0.8.1";
      url = "https://registry.npmjs.org/type-fest/-/type-fest-0.8.1.tgz";
      integrity = "sha512-4dbzIzqvjtgiM5rw1k5rEHtBANKmdudhGyBEajN01fEyhaAIhsoKNy6y7+IN93IfpFtwY9iqi7kD+xwKhQsNJA==";
    };

    "typescript@5.9.3" = {
      pname = "typescript";
      version = "5.9.3";
      url = "https://registry.npmjs.org/typescript/-/typescript-5.9.3.tgz";
      integrity = "sha512-jl1vZzPDinLr9eUt3J/t7V6FgNEw9QjvBPdysz9KfQDD41fQrC2Y4vKQdiaUpFT4bXlb1RHhLpp8wtm6M5TgSw==";
      hasBin = true;
    };

    "ufo@1.6.1" = {
      pname = "ufo";
      version = "1.6.1";
      url = "https://registry.npmjs.org/ufo/-/ufo-1.6.1.tgz";
      integrity = "sha512-9a4/uxlTWJ4+a5i0ooc1rU7C7YOw3wT+UGqdeNNHWnOF9qcMBgLRS+4IYUqbczewFx4mLEig6gawh7X6mFlEkA==";
    };

    "undici-types@6.21.0" = {
      pname = "undici-types";
      version = "6.21.0";
      url = "https://registry.npmjs.org/undici-types/-/undici-types-6.21.0.tgz";
      integrity = "sha512-iwDZqg0QAGrg9Rav5H4n0M64c3mkR59cJ6wQp+7C4nI0gsmExaedaYLNO44eT4AtBBwjbTiGPMlt2Md0T9H9JQ==";
    };

    "validate-npm-package-license@3.0.4" = {
      pname = "validate-npm-package-license";
      version = "3.0.4";
      url = "https://registry.npmjs.org/validate-npm-package-license/-/validate-npm-package-license-3.0.4.tgz";
      integrity = "sha512-DpKm2Ui/xN7/HQKCtpZxoRWBhZ9Z0kqtygG8XCgNQ8ZlDnxuQmWhj566j8fN4Cu3/JmbhsDo7fcAJq4s9h27Ew==";
      dependencies = [ "spdx-correct@3.2.0" "spdx-expression-parse@3.0.1" ];
    };

    "vite-node@1.6.1" = {
      pname = "vite-node";
      version = "1.6.1";
      url = "https://registry.npmjs.org/vite-node/-/vite-node-1.6.1.tgz";
      integrity = "sha512-YAXkfvGtuTzwWbDSACdJSg4A4DZiAqckWe90Zapc/sEX3XvHcw1NdurM/6od8J207tSDqNbSsgdCacBgvJKFuA==";
      dependencies = [ "pathe@1.1.2" "cac@6.7.14" "picocolors@1.1.1" "vite@5.4.21" "debug@4.4.3" ];
      hasBin = true;
    };

    "vite@5.4.21" = {
      pname = "vite";
      version = "5.4.21";
      url = "https://registry.npmjs.org/vite/-/vite-5.4.21.tgz";
      integrity = "sha512-o5a9xKjbtuhY6Bi5S3+HvbRERmouabWbyUcpXXUA1u+GNUKoROi9byOJ8M0nHbHYHkYICiMlqxkg1KkYmm25Sw==";
      dependencies = [ "esbuild@0.21.5" "rollup@4.53.3" "postcss@8.5.6" ];
      hasBin = true;
    };

    "vitest@1.6.1" = {
      pname = "vitest";
      version = "1.6.1";
      url = "https://registry.npmjs.org/vitest/-/vitest-1.6.1.tgz";
      integrity = "sha512-Ljb1cnSJSivGN0LqXd/zmDbWEM0RNNg2t1QW/XUhYl/qPqyu7CsqeWtqQXHVaJsecLPuDoak2oJcZN2QoRIOag==";
      dependencies = [ "@vitest/spy@1.6.1" "@vitest/expect@1.6.1" "@vitest/runner@1.6.1" "@vitest/snapshot@1.6.1" "tinypool@0.8.4" "pathe@1.1.2" "why-is-node-running@2.3.0" "local-pkg@0.5.1" "strip-literal@2.1.1" "magic-string@0.30.21" "vite@5.4.21" "debug@4.4.3" "vite-node@1.6.1" "picocolors@1.1.1" "std-env@3.10.0" "acorn-walk@8.3.4" "chai@4.5.0" "tinybench@2.9.0" "@vitest/utils@1.6.1" "execa@8.0.1" ];
      hasBin = true;
    };

    "which@2.0.2" = {
      pname = "which";
      version = "2.0.2";
      url = "https://registry.npmjs.org/which/-/which-2.0.2.tgz";
      integrity = "sha512-BLI3Tl1TW3Pvl70l3yq3Y64i+awpwXqsGBYWkkqMtnbXgrMD+yj7rhW0kuEDxzJaYXGjEW5ogapKNMEKNMjibA==";
      dependencies = [ "isexe@2.0.0" ];
      hasBin = true;
    };

    "why-is-node-running@2.3.0" = {
      pname = "why-is-node-running";
      version = "2.3.0";
      url = "https://registry.npmjs.org/why-is-node-running/-/why-is-node-running-2.3.0.tgz";
      integrity = "sha512-hUrmaWBdVDcxvYqnyh09zunKzROWjbZTiNy8dBEjkS7ehEDQibXJ7XvlmtbwuTclUiIyN+CyXQD4Vmko8fNm8w==";
      dependencies = [ "siginfo@2.0.0" "stackback@0.0.2" ];
      hasBin = true;
    };

    "wrappy@1.0.2" = {
      pname = "wrappy";
      version = "1.0.2";
      url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
      integrity = "sha512-l4Sp/DRseor9wL6EvV2+TuQn63dMkPjZ/sp9XkghTEbV9KlPS1xUsZ3u7/IQO4wxtcFB4bgpQPRcR3QCvezPcQ==";
    };

    "ws@8.18.3" = {
      pname = "ws";
      version = "8.18.3";
      url = "https://registry.npmjs.org/ws/-/ws-8.18.3.tgz";
      integrity = "sha512-PEIGCY5tSlUt50cqyMXfCzX+oOPqN0vuGqWzbcJ2xvnkzkq46oOpz7dQaTDBdfICb4N14+GARUDw2XV2N4tvzg==";
    };

    "yallist@4.0.0" = {
      pname = "yallist";
      version = "4.0.0";
      url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
      integrity = "sha512-3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
    };

    "yargs-parser@20.2.9" = {
      pname = "yargs-parser";
      version = "20.2.9";
      url = "https://registry.npmjs.org/yargs-parser/-/yargs-parser-20.2.9.tgz";
      integrity = "sha512-y11nGElTIV+CT3Zv9t7VKl+Q3hTQoT9a1Qzezhhl6Rp21gJ/IVTW7Z3y9EWXhuUBC2Shnf+DX0antecpAwSP8w==";
    };

    "yocto-queue@1.2.2" = {
      pname = "yocto-queue";
      version = "1.2.2";
      url = "https://registry.npmjs.org/yocto-queue/-/yocto-queue-1.2.2.tgz";
      integrity = "sha512-4LCcse/U2MHZ63HAJVE+v71o7yOdIe4cZ70Wpf8D/IyjDKYQLV5GD46B+hSTjJsvV5PztjvHoU580EftxjDZFQ==";
    };

    "zod@3.25.76" = {
      pname = "zod";
      version = "3.25.76";
      url = "https://registry.npmjs.org/zod/-/zod-3.25.76.tgz";
      integrity = "sha512-gzUt/qt81nXsFGKIFcC3YnfEAx5NkunCfnDlvuBSSFS02bcXu4Lmea0AFIUwbLWxWPx3d9p8S5QoaujKcNQxcQ==";
    };
  };
}
